<?php

namespace BasicDashboard\Foundations\Domain\Roles;
use App\Observers\AuditObserver;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;


/**
 *
 * A Role is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
#[ObservedBy([AuditObserver::class])]
class Role extends Model
{
    use HasFactory;
      //protected $table = 'table_name';
      protected $guarded = [

    ];

}
