<?php

namespace BasicDashboard\Foundations\Domain\DailyIncomes;
use App\Observers\AuditObserver;
use BasicDashboard\Foundations\Domain\DailyIncomeTotals\DailyIncomeTotal;
use Database\Factories\DailyIncomeFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use BasicDashboard\Foundations\Domain\OwnProducts\OwnProduct;



/**
 *
 * A DailyIncome is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
//if you want to audit this model uncomment below code and import
#[ObservedBy([AuditObserver::class])]
#[Fillable([
    'date',
    'name',
    'amount',
    'own_product_id',
    'price',
    'investment',
    'profit',
    'daily_income_total_id',
    'created_by',
    'updated_by',
    'deleted_by',
])]
class DailyIncome extends Model
{
    use HasFactory, SoftDeletes;

    protected static function newFactory()
    {
        return DailyIncomeFactory::new();
    }

      //protected $table = 'table_name';

    public function dailyIncomeTotal(): BelongsTo
    {
        return $this->belongsTo(DailyIncomeTotal::class);
    }

    public function ownProduct(): BelongsTo
    {
        return $this->belongsTo(OwnProduct::class);
    }



    // ==========================================
    // Query Scopes for Simplified Architecture
    // ==========================================
    // These scopes replace repository methods, allowing direct Eloquent usage in services
    
    /**
     * Scope to filter by keyword search
     */
    public function scopeFilterByKeyword(Builder $query, ?string $keyword): Builder
    {
        return $query->when($keyword, function (Builder $q) use ($keyword) {
            $q->where(function (Builder $sub) use ($keyword) {
                $sub->where('name', 'LIKE', '%' . $keyword . '%')
                    ->orWhereHas('ownProduct', function (Builder $q) use ($keyword) {
                        $q->where('name', 'LIKE', '%' . $keyword . '%');
                    })
                    ->orWhereHas('dailyIncomeTotal', function (Builder $q) use ($keyword) {
                        $q->where('voucher_no', 'LIKE', '%' . $keyword . '%');
                    });
            });
        });
    }

    public function scopeFilterByDateRange(Builder $query, ?string $from, ?string $to): Builder
    {
        return $query->when($from, fn(Builder $q) => $q->whereDate('date', '>=', $from))
            ->when($to, fn(Builder $q) => $q->whereDate('date', '<=', $to));
    }

    public function scopeFilterByInstant(Builder $query, mixed $isInstant): Builder
    {
        return $query->when($isInstant !== null && $isInstant !== '', function (Builder $q) use ($isInstant) {
            $q->whereHas('dailyIncomeTotal', function (Builder $sub) use ($isInstant) {
                $sub->where('is_instant', $isInstant);
            });
        });
    }

    /**
     * Scope to order by latest activity
     */
    public function scopeOrderByLatest(Builder $query): Builder
    {
        return $query->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderByDesc('id');
    }

}
