<?php

namespace BasicDashboard\Foundations\Domain\DailyIncomes;
use BasicDashboard\Foundations\Domain\Units\Unit;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use BasicDashboard\Foundations\Domain\OwnProducts\OwnProduct;



/**
 *
 * A DailyIncome is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
//if you want to audit this model uncomment below code and import
//#[ObservedBy([AuditObserver::class])]
class DailyIncome extends Model
{
    use HasFactory, SoftDeletes;
      //protected $table = 'table_name';
    protected $fillable = [
        'date',
        'name',
        'amount',
        'own_product_id',
        'price',
        'investment',
        'profit',
        'is_instant',
        'note',
        'created_by',
        'updated_by',
        'deleted_by',
    ];

    public function ownProduct()
    {
        return $this->belongsTo(OwnProduct::class);
    }



    // ==========================================
    // Query Scopes for Simplified Architecture
    // ==========================================
    // These scopes replace repository methods, allowing direct Eloquent usage in services
    
    /**
     * Scope to filter by keyword search
     * Searches in: name
     */
    public function scopeFilterByKeyword($query, ?string $keyword)
    {
        if (empty($keyword)) {
            return $query;
        }

        return $query->where('name', 'LIKE', '%' . $keyword . '%');
    }

    /**
     * Scope to order by latest activity
     */
    public function scopeOrderByLatest($query)
    {
        return $query->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderBy('id', 'desc');
    }

}
