<?php

namespace BasicDashboard\Mobile\Auth\Services;

use App\Exceptions\WarningException;
use BasicDashboard\Foundations\Domain\Users\User;
use BasicDashboard\Mobile\Auth\Resources\AuthResource;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

/**
 *
 * A AuthService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuthService
{

    public function __construct(
        private User $user
    )
    {
    }

    public function login(array $request): array
    {
      $user = $this->user->where('email', $request['email'])->first();
        if ($user) {
            if (! Hash::check($request['password'], $user->password)) {
                throw new WarningException("User credentials are not valid");
            }
        }

        if (Auth::attempt($request)) {
            $user = $this->user->where('email', $request['email'])->first();
            $userResource = new AuthResource($user);
            $token      = $user->createToken('auth_mobile_token')->plainTextToken;
            $grandToken = strpos($token, "|");
            $finalToken = substr($token, $grandToken + 1);
            
            return [
                'user_info' => $userResource,
                'token'     => $finalToken,
            ];
        } else {
            throw new WarningException("Wrong Credentials");
        }
    }

    public function logout(string $id): void
    {
        DB::table('personal_access_tokens')
            ->where('tokenable_id', $id)
            ->delete();
    }
}
