<?php

namespace BasicDashboard\Mobile\Auth\Services;

use App\Http\Controllers\Controller;
use BasicDashboard\Foundations\Domain\Users\User;
use BasicDashboard\Mobile\Auth\Resources\AuthResource;
use Illuminate\Http\JsonResponse;
use Illuminate\Routing\ResponseFactory;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

/**
 *
 * A AuthService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuthService extends Controller
{

    public function __construct(
        private ResponseFactory $responseFactory,
        private User $user
    )
    {
    }

    public function login(array $request): JsonResponse
    {
      $user = $this->user->where('email', $request['email'])->first();
        if ($user) {
            if (! Hash::check($request['password'], $user->password)) {
                return $this->responseFactory->sendAuthFailedResponse("User credentials are not valid");
            }
            
        }
        if (Auth::attempt($request)) {
            $user = $this->user->where('email', $request['email'])->first();
            $user = new AuthResource($user);
            $token      = $user->createToken('auth_frontend_token')->plainTextToken;
            $grandToken = strpos($token, "|");
            $finalToken = substr($token, $grandToken + 1);
            $data       = [
                'user_info' => $user,
                'token'     => $finalToken,
            ];
            return $this->responseFactory->sendSuccessResponse("Auth Data", $data);
        } else {
            return $this->responseFactory->sendAuthFailedResponse("Wrong Credentials");
        }
    }

    public function logout(string $id): JsonResponse
    {
        DB::table('personal_access_tokens')
            ->where('tokenable_id', $id)
            ->delete();
        return $this->responseFactory->sendSuccessResponse("Logout Success");
    }
}
