<?php
namespace BasicDashboard\Spa\Users\Services;

use BasicDashboard\Foundations\Domain\Users\Repositories\UserRepositoryInterface;
use BasicDashboard\Mobile\Users\Resources\UserResource;
use BasicDashboard\Spa\Common\BaseSpaController;
use Illuminate\Routing\ResponseFactory;


/**
 *
 * A UserService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UserService extends BaseSpaController
{
    public function __construct(
        private UserRepositoryInterface $userRepositoryInterface,
        private ResponseFactory $responseFactory,

    ) {
    }


    public function showUser(array $request): mixed
    {
        $data = $this->userRepositoryInterface->edit($request['user_id']);
        $data = new UserResource($data);
        $data = $data->response()->getData(true)['data'];
        return $this->responseFactory->sendSuccessResponse("Show success", $data);

    }

    
}
