<?php
namespace BasicDashboard\Web\Common;
use App\Http\Controllers\Controller;

/**
 *
 * A base controller for common method
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class BaseController extends Controller
{
    public function captureMemory(): int
    {
        return memory_get_usage();
    }

    public function calculateMemory($startMemory, $endMemory): string
    {
        $memoryUsed = round(($endMemory - $startMemory) / 1048576, 2);
        $memoryUsed .= ' mb';
        return $memoryUsed;
    }

    public function captureTime(): string
    {
        return microtime(true);
    }

    public function calculateTime($startTime, $endTime): string
    {
        $time = $endTime - $startTime;
        $time .= ' sec';
        return $time;
    }
}
