<?php
namespace BasicDashboard\Web\Common;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 *
 * A base controller for common method
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class BaseController extends Controller
{
    public function captureMemory(): int
    {
        return memory_get_usage();
    }

    public function calculateMemory($startMemory, $endMemory): string
    {
        $memoryUsed = round(($endMemory - $startMemory) / 1048576, 2);
        $memoryUsed .= ' mb';
        return $memoryUsed;
    }

    public function captureTime(): string
    {
        return microtime(true);
    }

    public function calculateTime($startTime, $endTime): string
    {
        $time = $endTime - $startTime;
        $time .= ' sec';
        return $time;
    }

    public function uploadImage($file, $directory, $privacy = 'public'): String
    {
        return Storage::disk('digitalocean')->putFile($directory, $file, $privacy);
    }

    public function deleteImage(string $directory): void
    {
        Storage::disk('digitalocean')->delete($directory);
    }

    

    public function reorder(Request $request)
    {
        $order = $request->order;

        if (empty($order)) {
            return response()->json(['message' => 'No items to reorder.'], 400);
        }

        $ids = collect($order)->pluck('id')->toArray();

        $cases = '';
        $model = '';
        foreach ($order as $item) {
            $id  = (int) $item['id'];
            $pos = (int) $item['position'];
            $cases .= "WHEN {$id} THEN {$pos} ";
            $model = $item['model'];
        }

        $idsList = implode(',', $ids);

        $query = "UPDATE {$model} SET sort_id = CASE id {$cases} END WHERE id IN ({$idsList})";
        \Log::info($query);

        DB::statement($query);

        return response()->json(['message' => 'Order updated successfully']);
    }

}
