<?php
namespace BasicDashboard\Foundations\Domain\Audits\Repositories;

use BasicDashboard\Foundations\Domain\Audits\Audit;
use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

/**
 *
 * A AuditRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface AuditRepositoryInterface extends BaseRepositoryInterface
{

    public function filterAudit(array $params): Builder | Audit;
    public function getAuditList($params): LengthAwarePaginator;
}
