<?php
/**
 *
 * A Audit is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

namespace BasicDashboard\Foundations\Domain\Audits;

use BasicDashboard\Foundations\Domain\Users\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Attributes\Fillable;

#[Fillable([
    'model',
    'event',
    'old_data',
    'new_data',
    'created_by',
    'created_at',
    'deleted_at'
])]

class Audit extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'audits';

    public $timestamps = false;

    /**
     * Optional: Cast JSON fields (recommended in Laravel 13)
     */
    protected $casts = [
        'old_data' => 'array',
        'new_data' => 'array',
        'created_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    /**
     * Relationship: Audit belongs to User
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by')
            ->withDefault([
                'name' => '---',
            ]);
    }

    // ==========================================
    // Query Scopes (Modern Typed Style)
    // ==========================================

    /**
     * Scope: Filter by keyword
     */
    public function scopeFilterByKeyword(Builder $query, ?string $keyword): Builder
    {
        return $query->when($keyword, function (Builder $q) use ($keyword) {
            $q->where(function (Builder $sub) use ($keyword) {
                $sub->where('model', 'like', "%{$keyword}%")
                    ->orWhere('event', 'like', "%{$keyword}%");
            });
        });
    }

    /**
     * Scope: Order by latest
     */
    public function scopeOrderByLatest(Builder $query): Builder
    {
        return $query
            ->orderByDesc('created_at')
            ->orderByDesc('id');
    }
}