<?php

namespace BasicDashboard\Web\Products\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A DeleteProductRequest is responsible validation of id while deleting.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DeleteProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
          "id"=>"required",
        ];
    }

    public function messages(): array
    {
        return [
            "id.required" => "Product ID is required",
        ];
    }
}
