<?php

namespace BasicDashboard\Web\Products\Validation;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

/**
 *
 * A StoreProductRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'created_by' => Auth::id(),
        ]);
    }

    public function rules(): array
    {
        return [
            "name" => "required|string|max:255",
            "name_other" => "required|string|max:255",
            "price" => "required|numeric",
            "description" => "nullable|string",
            "description_other" => "nullable|string",
            "photos" => "required|array",
            "photos.*" => "image|mimes:jpeg,png,jpg,gif,svg|max:2048",
            "categories" => "required|array",
            "categories.*" => "exists:categories,id",
            "created_by"=> "nullable",
        ];
    }   
}
