<?php

namespace BasicDashboard\Web\Products\Validation;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

/**
 *
 * A StoreProductRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'is_banner' => $this->boolean('is_banner') ? 1 : 0,
            'is_mini_banner' => $this->boolean('is_mini_banner') ? 1 : 0,
            'price' => str_replace(',', '', $this->price),
        ]);
    
    }

    public function rules(): array
    {
        return [
            "name" => "required|string|max:255",
            "name_other" => "required|string|max:255",
            "price" => "required|numeric",
            "description" => "nullable|string",
            "description_other" => "nullable|string",
            "photos" => "required|array",
            "photos.*" => "image|mimes:jpeg,png,jpg,gif,svg|max:2048",
            "categories" => "required|array",
            "categories.*" => "exists:categories,id",
            "is_banner" => "nullable|boolean",
            "is_mini_banner" => "nullable|boolean",
            "created_by"=> "nullable",
        ];
    }

    public function messages(): array
    {
        return [
            "name.required" => "Product Name is required",
            "name_other.required" => "Product Name (Other) is required",
            "price.required" => "Product Price is required",
            "photos.required" => "At least one product photo is required",
            "categories.required" => "At least one category is required",
        ];
    }
}
