<?php

namespace BasicDashboard\Web\Products\Validation;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

/**
 *
 * A UpdateProductRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'updated_by' => Auth::id(),
        ]);
    }
    public function rules(): array
    {
        return [
            "name" => "required|string|max:255",
            "name_other" => "required|string|max:255",
            "price" => "required|numeric",
            "description" => "nullable|string",
            "description_other" => "nullable|string",
            "photos" => "nullable|array",
            "photos.*" => "image|mimes:jpeg,png,jpg,gif,svg|max:2048",
            "existing_photos" => "nullable|array",
            "existing_photos.*" => "string",
            "updated_by" => "nullable",
            "categories" => "required|array",
            "categories.*" => "exists:categories,id",
        ];
    }

   
}
