<?php

namespace BasicDashboard\Web\OwnProducts\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A DeleteOwnProductRequest is responsible validation of id while deleting.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DeleteOwnProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'id' => $this->route('own_product'),
        ]);
    }

    public function rules(): array
    {
        return [
          "id"=>"required",
        ];
    }
}
