<?php

namespace BasicDashboard\Web\OwnProducts\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreOwnProductRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreOwnProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "name"=>"required",
            "unit_id"=>"required|exists:units,id",
            "category_id"=>"required|exists:categories,id",
            "price"=>"required|numeric",
            "investment"=>"required|numeric",
            "profit"=>"required|numeric",
            "image"=>"required|image|mimes:jpeg,png,jpg,gif|max:2048",
        ];
    }

    public function messages(): array
    {
        return [
            "name.required"=>"Name is required",
            "unit_id.required"=>"Unit is required",
            "category_id.required"=>"Category is required",
            "price.required"=>"Price is required",
            "investment.required"=>"Investment is required",
            "profit.required"=>"Profit is required",
            "image.required"=>"Image is required",
            "image.image"=>"Image must be an image",
            "image.mimes"=>"Image must be a jpeg, png, jpg, gif",
            "image.max"=>"Image must be less than 2MB",
        ];
    }
}
