<?php

namespace BasicDashboard\Web\OwnProducts\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreOwnProductRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreOwnProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "name"=>"required",
            "unit_id"=>"required|exists:units,id",
            "category_id"=>"required|exists:categories,id",
            "price"=>"required|numeric",
            "investment"=>"required|numeric",
            "profit"=>"required|numeric",
        ];
    }
}
