<?php
namespace BasicDashboard\Foundations\Domain\Roles\Repositories;

use Spatie\Permission\Models\Role;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;

/**
 *
 * A RoleRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface RoleRepositoryInterface extends BaseRepositoryInterface
{
    public function filterRole(array $params): Builder | Role;
    public function getRoleList($params): LengthAwarePaginator;
}
