<?php

namespace BasicDashboard\Web\Products\Controllers;

use BasicDashboard\Foundations\Shared\BaseCrudController;
use BasicDashboard\Web\Products\Services\ProductService;
use BasicDashboard\Web\Products\Validation\StoreProductRequest;
use BasicDashboard\Web\Products\Validation\UpdateProductRequest;
use BasicDashboard\Web\Products\Validation\DeleteProductRequest;
use Illuminate\Routing\ResponseFactory;
use BasicDashboard\Web\Products\Resources\ProductResource;

/**
 *
 * A ProductController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ProductController extends BaseCrudController
{
    protected string $viewPath = 'admin.product';
    protected string $routePrefix = 'products';
    protected string $langPath = "product.product";
    protected string $resourceClass = ProductResource::class;

    public function __construct(
        protected ProductService $productService,
        protected ResponseFactory $responseFactory
    ) {
        parent::__construct($responseFactory);
        $this->service = $productService;
    }

    public function store(StoreProductRequest $request)
    {
        return parent::performStore($request);
    }

    public function update(UpdateProductRequest $request, string $id)
    {
        return parent::performUpdate($request, $id);
    }

    public function destroy(DeleteProductRequest $request)
    {
        return parent::performDestroy($request);
    }
}
