<?php

namespace BasicDashboard\Web\Products\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Web\Products\Services\ProductService;
use BasicDashboard\Web\Products\Validation\StoreProductRequest;
use BasicDashboard\Web\Products\Validation\UpdateProductRequest;
use BasicDashboard\Web\Products\Validation\DeleteProductRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 *
 * A ProductController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ProductController extends Controller
{
    public function __construct(
        private ProductService $productService
    ) {
    }

    public function index(Request $request): View
    {
        return $this->productService->index($request->all());
    }

    public function create(): View
    {
        return $this->productService->create();
    }

    public function store(StoreProductRequest $request)
    {
        return $this->productService->store($request->validated());
    }

    public function edit(string $id): View | RedirectResponse
    {
        return $this->productService->edit($id);
    }

    public function show(string $id): View | RedirectResponse
    {
        return $this->productService->show($id);
    }

    public function update(UpdateProductRequest $request, string $id)
    {
        return $this->productService->update($request->validated(), $id);
    }

    public function destroy(DeleteProductRequest $request)
    {
        return $this->productService->destroy($request->validated());
    }

}
