<?php

namespace BasicDashboard\Foundations\Domain\OwnProducts;
use App\Observers\AuditObserver;
use BasicDashboard\Foundations\Domain\Categories\Category;
use BasicDashboard\Foundations\Domain\Units\Unit;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;


/**
 *
 * A OwnProduct is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
//if you want to audit this model uncomment below code and import
#[ObservedBy([AuditObserver::class])]
#[Fillable([
    'name',
    'unit_id',
    'category_id',
    'price',
    'investment',
    'profit',
    'image',
    'created_by',
    'updated_by',
    'deleted_by',
])]
class OwnProduct extends Model
{
    use HasFactory, SoftDeletes;

    protected static function newFactory()
    {
        return \Database\Factories\OwnProductFactory::new();
    }

      //protected $table = 'table_name';

    public function unit(): BelongsTo
    {
        return $this->belongsTo(Unit::class);
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }


    // ==========================================
    // Query Scopes for Simplified Architecture
    // ==========================================
    // These scopes replace repository methods, allowing direct Eloquent usage in services
    
    /**
     * Scope to filter by keyword search
     */
    public function scopeFilterByKeyword(Builder $query, ?string $keyword): Builder
    {
        return $query->when($keyword, function (Builder $q) use ($keyword) {
            $q->where(function (Builder $sub) use ($keyword) {
                $sub->where('name', 'LIKE', '%' . $keyword . '%')
                    ->orWhereHas('category', function (Builder $q) use ($keyword) {
                        $q->where('name', 'LIKE', '%' . $keyword . '%');
                    });
            });
        });
    }

    /**
     * Scope to order by latest activity
     */
    public function scopeOrderByLatest(Builder $query): Builder
    {
        return $query->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderByDesc('id');
    }

    public function dailyIncomes(): HasMany
    {
        return $this->hasMany(\BasicDashboard\Foundations\Domain\DailyIncomes\DailyIncome::class);
    }

    public function hasDailyIncomes(): bool
    {
        return $this->dailyIncomes()->exists();
    }
}
