<?php

namespace BasicDashboard\Spa\Categories\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Spa\Categories\Services\CategoryService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;



/**
 *
 * A CategoryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * @tags Spa
 *
 */

class CategoryController extends Controller
{
    public function __construct(
        private CategoryService $categoryService
    ) {
    }

    public function index(Request $request): JsonResponse
    {
        return $this->categoryService->index($request->all());
    }


    public function show(string $id): JsonResponse
    {
        return $this->categoryService->show($id);
    }

}
