<?php

namespace BasicDashboard\Web\Units\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A DeleteUnitRequest is responsible validation of id while deleting.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DeleteUnitRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }
     protected function prepareForValidation(): void
    {
        $this->merge([
            'id' => $this->route('unit'),
        ]);
    }


    public function rules(): array
    {
        return [
          "id"=>"required",
        ];
    }

     public function messages(): array
    {
        return [
            "id.required" => "Role ID is required",
        ];
    }
}
