<?php

namespace BasicDashboard\Web\Units\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateUnitRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateUnitRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
          "name"=>"required",
          "description" =>"nullable",
        ];
    }

    public function messages():array {
        return [
            'name.required' => __('unit.name_validation'),
        ];
    }
}
