<?php

namespace BasicDashboard\Web\DailyIncomes\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreDailyIncomeRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreDailyIncomeRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'is_instant' => $this->boolean('is_instant') ? 1 : 0,
        ]);
    }

    public function rules(): array
    {
        return [
            "date" => "required|date",
            "name" => "required|string",
            "own_product_id" => "required|exists:own_products,id",
            "amount" => "required|numeric",
            "unit_id" => "required|exists:units,id",
            "price" => "required|numeric",
            "investment" => "required|numeric",
            "profit" => "required|numeric",
            "is_instant" => "nullable|boolean",
            "note" => "nullable|string",

        ];
    }
}
