<?php

namespace BasicDashboard\Web\DailyIncomes\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreDailyIncomeRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreDailyIncomeRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'is_instant' => $this->boolean('is_instant') ? 1 : 0,
        ]);
    }

    public function rules(): array
    {
        return [
            "date" => "required|date",
            "own_product_id" => "required|array|min:1",
            "own_product_id.*" => "required|exists:own_products,id",
            "amount" => "required|array|min:1",
            "amount.*" => "required|numeric|min:0.01",
            "unit_id" => "required|array|min:1",
            "unit_id.*" => "required|exists:units,id",
            "price" => "required|array|min:1",
            "price.*" => "required|numeric",
            "investment" => "required|array|min:1",
            "investment.*" => "required|numeric",
            "profit" => "required|array|min:1",
            "profit.*" => "required|numeric",
            "is_instant" => "nullable|boolean",
            "note" => "nullable|string",
        ];
    }

    public function messages():array{
        return [
            "date.required" => "Date is required",
            "own_product_id.required" => "Own Product is required",
            "own_product_id.*.required" => "Product selection is required",
            "amount.required" => "Amount is required",
            "amount.*.required" => "Amount is required for all items",
            "unit_id.required" => "Unit is required",
            "price.required" => "Price is required",
            "investment.required" => "Investment is required",
            "profit.required" => "Profit is required",
        ];
    }
}
