<?php

namespace BasicDashboard\Web\DailyIncomes\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateDailyIncomeRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateDailyIncomeRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        if ($this->has('items')) {
            $items = $this->input('items');
            foreach ($items as &$item) {
                if (isset($item['price'])) $item['price'] = str_replace(',', '', $item['price']);
                if (isset($item['investment'])) $item['investment'] = str_replace(',', '', $item['investment']);
                if (isset($item['profit'])) $item['profit'] = str_replace(',', '', $item['profit']);
                if (isset($item['amount'])) $item['amount'] = str_replace(',', '', $item['amount']);
            }
            $this->merge(['items' => $items]);
        }

        $this->merge([
            'is_instant' => $this->boolean('is_instant') ? 1 : 0,
            'warehouse_id' => $this->filled('warehouse_id') ? customDecoder($this->input('warehouse_id')) : null,
        ]);
    }

    public function rules(): array
    {
        return [
            "warehouse_id" => "nullable|exists:warehouses,id",
            "date" => "required|date",
            "items" => "required|array|min:1",
            "items.*.own_product_id" => "required|exists:own_products,id",
            "items.*.amount" => "required|numeric|min:0.01",
            "items.*.price" => "required|numeric",

            "items.*.investment" => "required|numeric",
            "items.*.profit" => "required|numeric",
            "is_instant" => "nullable|boolean",
            "note" => "nullable|string",
        ];
    }
}
