<?php

namespace BasicDashboard\Web\DailyIncomes\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateDailyIncomeRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateDailyIncomeRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        if (!$this->has('items') && $this->has('own_product_id')) {
            $items = [];
            foreach ($this->input('own_product_id') as $index => $productId) {
                $items[] = [
                    'product_id' => $productId,
                    'amount' => str_replace(',', '', $this->input('amount')[$index] ?? 0),
                    'unit_id' => $this->input('unit_id')[$index] ?? null,
                    'price' => str_replace(',', '', $this->input('price')[$index] ?? 0),
                    'investment' => str_replace(',', '', $this->input('investment')[$index] ?? 0),
                    'profit' => str_replace(',', '', $this->input('profit')[$index] ?? 0),
                ];
            }
            $this->merge(['items' => $items]);
        }

        if ($this->has('items')) {
            $items = $this->input('items');
            foreach ($items as &$item) {
                if (isset($item['price'])) $item['price'] = str_replace(',', '', $item['price']);
                if (isset($item['investment'])) $item['investment'] = str_replace(',', '', $item['investment']);
                if (isset($item['profit'])) $item['profit'] = str_replace(',', '', $item['profit']);
                if (isset($item['amount'])) $item['amount'] = str_replace(',', '', $item['amount']);
            }
            $this->merge(['items' => $items]);
        }

        $this->merge([
            'is_instant' => $this->boolean('is_instant') ? 1 : 0,
        ]);
    }

    public function rules(): array
    {
        return [
            "date" => "required|date",
            "items" => "required|array|min:1",
            "items.*.product_id" => "required|exists:own_products,id",
            "items.*.amount" => "required|numeric|min:0.01",
            "items.*.unit_id" => "required|exists:units,id",
            "items.*.price" => "required|numeric",
            "items.*.investment" => "required|numeric",
            "items.*.profit" => "required|numeric",
            "is_instant" => "nullable|boolean",
            "note" => "nullable|string",
        ];
    }
}
