<?php

namespace BasicDashboard\Web\Roles\Validation;

use Spatie\Permission\Models\Permission;
use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreRoleRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreRoleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'can_access_panel' => $this->boolean('can_access_panel') ? 1 : 0,
        ]);
    }

    public function rules(): array
    {
        return [
            "name"=>"required|max:255",
            "permissions" =>"required",
            "can_access_panel" => ""
        ];
    }

    /**
     * Get the error messages for the defined validation rules.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'permissions.required' =>  __('role.permission_validation'),
            'name.required' => __('role.role_name_validation'),
        ];
    }
    
}
