<?php

namespace BasicDashboard\Web\Roles\Validation;

use Spatie\Permission\Models\Permission;
use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateRoleRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateRoleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->offsetUnset('_token');
        $removeName = array_slice($this->all(),1); //remove 'Name' key
        $getKeys = array_keys($removeName); // get array [p_1,p_2]
        $arrayWithId = array_map(fn($value): string => substr($value,2),$getKeys); // [1,2]
        $permissions = Permission::whereIn('id',$arrayWithId)->pluck('name')->toArray(); // ['manage users','create users']
        $this->merge([
            'permissions' => $permissions
        ]);
        
        if($this->can_access_panel=='on') {
            $this->merge([
                'can_access_panel' => 1
            ]);
        }else{
            $this->merge([
                'can_access_panel' => 0
            ]);
        }
    }

    public function rules(): array
    {
        return [
          "name"=>"required|max:255",
          "permissions" => "required",
          "can_access_panel" => ""
        ];
    }
}
