<?php

namespace BasicDashboard\Web\Roles\Validation;

use Spatie\Permission\Models\Permission;
use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateRoleRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateRoleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'can_access_panel' => $this->boolean('can_access_panel') ? 1 : 0,
        ]);
    }

    public function rules(): array
    {
        return [
          "name"=>"required|max:255",
          "permissions" => "required",
          "can_access_panel" => ""
        ];
    }

    public function messages(): array
    {
        return [
            "name.required" => "Role Name is required",
            "permissions.required" => "At least one permission is required",
        ];
    }
}
