<?php

namespace BasicDashboard\Web\OwnProducts\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A OwnProductResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class OwnProductResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" =>customEncoder($this->id),
            "name"=>$this->name,
            "unit_id"=>$this->unit_id,
            "category_id"=>$this->category_id,
            "unit"=>$this->unit?->name,
            "category"=>$this->category?->name,
            "price"=>$this->price,
            "investment"=>$this->investment,
            "profit"=>$this->profit,
        ];
    }
}
