<?php

namespace BasicDashboard\Foundations\Domain\Products;
use App\Observers\AuditObserver;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use BasicDashboard\Foundations\Domain\Categories\Category;


/**
 *
 * A Product is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
//if you want to audit this model uncomment below code and import
#[ObservedBy([AuditObserver::class])]
#[Fillable([
    'name',
    'name_other',
    'price',
    'photos',
    'description',
    'description_other',
    'is_banner',
    'is_mini_banner',
    'created_at',
    'updated_at',
    'deleted_at',
    'created_by',
    'updated_by',
    'deleted_by',
])]
class Product extends Model
{
    use HasFactory;

    protected static function newFactory()
    {
        return \Database\Factories\ProductFactory::new();
    }
      //protected $table = 'table_name';

    protected $casts = [
        'photos' => 'array',
        'is_banner' => 'boolean',
        'is_mini_banner' => 'boolean',
    ];

    // ==========================================
    // Query Scopes for Simplified Architecture
    // ==========================================
    // These scopes replace repository methods, allowing direct Eloquent usage in services
    
    /**
     * Scope to filter by keyword search
     * Searches in: name
     */
    /**
     * Scope to filter by keyword search
     */
    public function scopeFilterByKeyword(Builder $query, ?string $keyword): Builder
    {
        return $query->when($keyword, function (Builder $q) use ($keyword) {
            $q->where('name', 'LIKE', '%' . $keyword . '%');
        });
    }

    /**
     * Scope to filter by category ID
     */
    public function scopeFilterByCategory(Builder $query, ?int $categoryId): Builder
    {
        return $query->when($categoryId, function (Builder $q) use ($categoryId) {
            $q->whereHas('categories', function (Builder $sub) use ($categoryId) {
                $sub->where('categories.id', $categoryId);
            });
        });
    }

    /**
     * Scope to order by latest activity
     */
    public function scopeOrderByLatest(Builder $query): Builder
    {
        return $query->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderByDesc('id');
    }

    public function scopeGetBannerData(Builder $query, ?int $limit = 2): \Illuminate\Database\Eloquent\Collection
    {
        return $query->where('is_banner', true)->limit($limit)->orderByDesc('id')->get();
    }

    public function scopeGetMiniBannerData(Builder $query, ?int $limit = 4): \Illuminate\Database\Eloquent\Collection
    {
        return $query->where('is_mini_banner', true)->limit($limit)->orderByDesc('id')->get();
    }

    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class, 'category_product');
    }

}
