<?php
namespace BasicDashboard\Foundations\Domain\Categories\Repositories;

use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;
use BasicDashboard\Foundations\Domain\Categories\Category;


/**
 *
 * A CategoryRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface CategoryRepositoryInterface extends BaseRepositoryInterface
{
    public function filterCategory(array $params): Builder | Category;
    public function getCategoryList($params): LengthAwarePaginator;
}