<?php

namespace BasicDashboard\Web\Categories\Services;

use BasicDashboard\Foundations\Domain\Categories\Repositories\CategoryRepositoryInterface;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Categories\Resources\CategoryResource;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;
use Illuminate\View\View;
use Exception;

/**
 *
 * A CategoryService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CategoryService extends BaseController
{
    const VIEW = 'admin.category';
    const ROUTE = 'categories';
    const LANG_PATH = "category.category";

    public function __construct(
        private CategoryRepositoryInterface $categoryRepositoryInterface,
        private ResponseFactory $responseFactory
    )
    {
    }

    public function index(array $request): View
    {
        $categoryList = $this->categoryRepositoryInterface->getCategoryList($request);
        $categoryList = CategoryResource::collection($categoryList)->response()->getData(true);
        return $this->responseFactory->successView(self::VIEW.".index", $categoryList);
    }

    public function create(): View
    {
        return view(self::VIEW.'.create');
    }

    public function store($request): RedirectResponse
    {
        try {
            $this->categoryRepositoryInterface->beginTransaction();
            $this->categoryRepositoryInterface->insert($request);
            $this->categoryRepositoryInterface->commit();
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_created'));
        } catch (Exception $e) {
            return $this->responseFactory->redirectBackWithError($this->categoryRepositoryInterface, $e->getMessage());
        }
    }

    public function edit(string $id): View | RedirectResponse
    {
        $category = $this->categoryRepositoryInterface->edit($id);
        $category = new CategoryResource($category);
        $category = $category->response()->getData(true)['data'];
        return $this->responseFactory->successView(self::VIEW . ".edit", $category);
    }

    public function show(string $id): View | RedirectResponse
    {
        $category = $this->categoryRepositoryInterface->show($id);
        $category = new CategoryResource($category);
        $category = $category->response()->getData(true)['data'];
        return $this->responseFactory->successView(self::VIEW . '.show', $category);
    }

    public function update($request, string $id): RedirectResponse
    {
         try {
            $this->categoryRepositoryInterface->beginTransaction();
            $this->categoryRepositoryInterface->update($request, $id);
            $this->categoryRepositoryInterface->commit();
            return $this->responseFactory->successShowRedirect(self::ROUTE, $id, __(self::LANG_PATH . '_updated'));
        } catch (Exception $e) {
            return $this->responseFactory->redirectBackWithError($this->categoryRepositoryInterface, $e->getMessage());
        }
    }

    public function destroy($request): RedirectResponse
    {
         try {
            $this->categoryRepositoryInterface->beginTransaction();
            $this->categoryRepositoryInterface->delete($request['id']);
            $this->categoryRepositoryInterface->commit();
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_deleted'));
        } catch (Exception $e) {
            return $this->responseFactory->redirectBackWithError($this->categoryRepositoryInterface, $e->getMessage());
        }
    }

}
