<?php

namespace BasicDashboard\Mobile\Auth\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Mobile\Auth\Services\AuthService;
use BasicDashboard\Mobile\Auth\Validation\LoginRequest;
use BasicDashboard\Mobile\Auth\Validation\LogoutRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Routing\ResponseFactory;
use App\Exceptions\WarningException;
use Throwable;

/**
 *
 * A CategoryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * @tags Mobile
 *
 */

class AuthController extends Controller
{
    public function __construct(
        private AuthService $authService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function login(LoginRequest $request): JsonResponse
    {
        try {
            $data = $this->authService->login($request->validated());
            return $this->responseFactory->sendSuccessResponse("Login Success", $data);
        } catch (WarningException $e) {
            return $this->responseFactory->sendAuthFailedResponse($e->getMessage());
        } catch (Throwable $e) {
            return $this->responseFactory->sendErrorResponse($e->getMessage());
        }
    }


    public function logout(LogoutRequest $request): JsonResponse
    {
        try {
            $this->authService->logout($request->validated()['id']);
            return $this->responseFactory->sendSuccessResponse("Logout Success");
        } catch (Throwable $e) {
            return $this->responseFactory->sendErrorResponse($e->getMessage());
        }
    }

}
