<?php

namespace BasicDashboard\Mobile\Auth\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Mobile\Auth\Services\AuthService;
use BasicDashboard\Mobile\Auth\Validation\LoginRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;



/**
 *
 * A CategoryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * @tags Mobile
 *
 */

class AuthController extends Controller
{
    public function __construct(
        private AuthService $authService
    ) {
    }

    public function login(LoginRequest $request): JsonResponse
    {
        return $this->authService->login($request->validated());
    }


    public function logout(string $id): JsonResponse
    {
        return $this->authService->logout($id);
    }

}
