<?php

namespace BasicDashboard\Web\DailyIncomes\Controllers;

use BasicDashboard\Foundations\Domain\DailyIncomes\DailyIncome;
use BasicDashboard\Foundations\Domain\OwnProducts\OwnProduct;
use BasicDashboard\Web\Common\BaseController;

use BasicDashboard\Web\DailyIncomes\Resources\DailyIncomeResource;
use BasicDashboard\Web\DailyIncomes\Services\DailyIncomeService;
use BasicDashboard\Web\DailyIncomes\Validation\StoreDailyIncomeRequest;
use BasicDashboard\Web\DailyIncomes\Validation\UpdateDailyIncomeRequest;
use BasicDashboard\Web\DailyIncomes\Validation\DeleteDailyIncomeRequest;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Inertia\Inertia;
use Inertia\Response;
use Throwable;
use Illuminate\Support\Facades\Log;
use Maatwebsite\Excel\Facades\Excel;
use BasicDashboard\Web\DailyIncomes\Imports\DailyIncomesImport;
use BasicDashboard\Web\DailyIncomes\Exports\DailyIncomesSampleExport;


/**
 *
 * A DailyIncomeController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DailyIncomeController extends BaseController
{
    const VIEW = 'admin.daily-income';
    const ROUTE = 'daily-incomes';
    const LANG_PATH = "dailyIncome.dailyIncome";

    public function __construct(
        private DailyIncomeService $dailyIncomeService
    ) {
    }

    public function index(Request $request): Response
    {
        $dailyIncomeList = $this->dailyIncomeService->paginate($request->all());
        $dailyIncomeList = DailyIncomeResource::collection($dailyIncomeList)->response()->getData(true);
        return Inertia::render('DailyIncomes/Index',  array_merge($dailyIncomeList, [
            'filters' => $request->only(['keyword', 'is_instant'])
        ]));
    }

    public function create(): Response
    {
        return Inertia::render('DailyIncomes/CreateEdit', [
            'products' => [],
        ]);
    }

    public function store(StoreDailyIncomeRequest $request): RedirectResponse
    {
        try {
            $this->dailyIncomeService->store($request->validated());
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_created'));
        } catch (Throwable $e) {
            $this->LogError("DailyIncome store failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function edit(DailyIncome $dailyIncome): Response
    {
        $items = $this->dailyIncomeService->getByVoucherNo($dailyIncome);

        $formattedItems = DailyIncomeResource::collection($items)->response()->getData(true)['data'];
        $data = [
            'id' => customEncoder($dailyIncome->id),
            'date' => $dailyIncome->date,
            'is_instant' => $dailyIncome->dailyIncomeTotal?->is_instant ?? true,
            'note' => $dailyIncome->dailyIncomeTotal?->note,
            'items' => $formattedItems,
            'voucher_no' => $dailyIncome->dailyIncomeTotal?->voucher_no,
            'total_price' => number_format($dailyIncome->dailyIncomeTotal?->total_price ??0,2,'.',''),
            'total_investment' => number_format($dailyIncome->dailyIncomeTotal?->total_investment ??0,2,'.',''),
            'total_profit' => number_format($dailyIncome->dailyIncomeTotal?->total_profit ??0,2,'.',''),
        ];

        // For editing, we should pass the products that are already in the voucher
        // so the SearchableSelect can show the correct initial labels.
        $productIds = $items->pluck('own_product_id')->unique();
        $products = OwnProduct::whereIn('id', $productIds)
            ->with('unit')
            ->get();

        return Inertia::render('DailyIncomes/CreateEdit', [
            'dailyIncome' => $data,
            'products' => $products,
        ]);
    }

    public function show(DailyIncome $dailyIncome): Response
    {
        $items = $this->dailyIncomeService->getByVoucherNo($dailyIncome);

        $formattedItems = DailyIncomeResource::collection($items)->response()->getData(true)['data'];
        $data = [
            'id' => customEncoder($dailyIncome->id),
            'date' => $dailyIncome->date,
            'is_instant' => $dailyIncome->dailyIncomeTotal?->is_instant ?? true,
            'note' => $dailyIncome->dailyIncomeTotal?->note,
            'items' => $formattedItems,
            'voucher_no' => $dailyIncome->dailyIncomeTotal?->voucher_no,
        ];

        return Inertia::render('DailyIncomes/Show', [
            'dailyIncome' => $data,
        ]);
    }

    public function update(UpdateDailyIncomeRequest $request, DailyIncome $dailyIncome): RedirectResponse
    {
        try {
            $this->dailyIncomeService->update($request->validated(), $dailyIncome->id);
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_updated'));
        } catch (Throwable $e) {
            $this->LogError("DailyIncome update failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function destroy(DeleteDailyIncomeRequest $request, DailyIncome $dailyIncome): RedirectResponse
    {
        try {
            $this->dailyIncomeService->delete($dailyIncome->id);
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_deleted'));
        } catch (Throwable $e) {
            $this->LogError("DailyIncome destroy failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function importView(): Response
    {
        return Inertia::render('DailyIncomes/ExcelImport');
    }

    public function downloadSample()
    {
        return Excel::download(new DailyIncomesSampleExport, 'daily_incomes_sample.xlsx');
    }

    public function import(Request $request): RedirectResponse
    {
        $request->validate([
            'file' => 'required|mimes:xlsx,xls,csv|max:2048'
        ]);

        try {
            Excel::import(new DailyIncomesImport($this->dailyIncomeService), $request->file('file'));
            return redirect()->route(self::ROUTE . '.index')->with('success', 'Excel imported successfully.');
        } catch (Throwable $e) {
            Log::error("DailyIncome import failed", ['error' => $e->getMessage()]);
            return back()->with('error', 'Import failed: ' . $e->getMessage());
        }
    }
}
