<?php

namespace BasicDashboard\Web\DailyIncomes\Controllers;

use BasicDashboard\Foundations\Shared\BaseCrudController;
use BasicDashboard\Web\DailyIncomes\Resources\DailyIncomeResource;
use BasicDashboard\Web\DailyIncomes\Services\DailyIncomeService;
use BasicDashboard\Web\DailyIncomes\Validation\StoreDailyIncomeRequest;
use BasicDashboard\Web\DailyIncomes\Validation\UpdateDailyIncomeRequest;
use BasicDashboard\Web\DailyIncomes\Validation\DeleteDailyIncomeRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;

/**
 *
 * A DailyIncomeController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DailyIncomeController extends BaseCrudController
{
    protected string $viewPath = 'admin.daily-income';
    protected string $routePrefix = 'daily-incomes';
    protected string $langPath = "daily_income.daily_income";
    protected string $resourceClass = DailyIncomeResource::class;

    public function __construct(
        protected DailyIncomeService $dailyIncomeService,
        protected ResponseFactory $responseFactory
    ) {
        parent::__construct($responseFactory);
        $this->service = $dailyIncomeService;
    }

    public function store(StoreDailyIncomeRequest $request): RedirectResponse
    {
        return parent::performStore($request);
    }

    public function update(UpdateDailyIncomeRequest $request, string $id): RedirectResponse
    {
        return parent::performUpdate($request, $id);
    }

    public function destroy(DeleteDailyIncomeRequest $request): RedirectResponse
    {
        return parent::performDestroy($request);
    }
}
