<?php

namespace BasicDashboard\Web\DailyIncomes\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\DailyIncomes\Resources\DailyIncomeResource;
use BasicDashboard\Web\DailyIncomes\Services\DailyIncomeService;
use BasicDashboard\Web\DailyIncomes\Validation\StoreDailyIncomeRequest;
use BasicDashboard\Web\DailyIncomes\Validation\UpdateDailyIncomeRequest;
use BasicDashboard\Web\DailyIncomes\Validation\DeleteDailyIncomeRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;


/**
 *
 * A DailyIncomeController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DailyIncomeController extends BaseController
{
    const VIEW = 'admin.daily-income';
    const ROUTE = 'daily-incomes';
    const LANG_PATH = "daily_income.daily_income";

    public function __construct(
        private DailyIncomeService $dailyIncomeService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function index(Request $request): View
    {
        $dailyIncomeList = $this->dailyIncomeService->paginate($request->all());
        $dailyIncomeList = DailyIncomeResource::collection($dailyIncomeList)->response()->getData(true);
        return $this->responseFactory->successView(self::VIEW . '.index', $dailyIncomeList);
    }

    public function create(): View
    {
        return view(self::VIEW . '.create');
    }

    public function store(StoreDailyIncomeRequest $request): RedirectResponse
    {
        try {
            $this->dailyIncomeService->store($request->all());
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_created'));
        } catch (\Throwable $e) {
            $this->LogError("DailyIncome store failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

    public function edit(string $id): View | RedirectResponse
    {
        $decodedId = customDecoder($id);
        $dailyIncome = $this->dailyIncomeService->findOrFail($decodedId);
        $dailyIncome = new DailyIncomeResource($dailyIncome);
        $dailyIncome = $dailyIncome->response()->getData(true)['data'];
        return $this->responseFactory->successView(self::VIEW . ".edit", $dailyIncome);

    }

    public function show(string $id): View | RedirectResponse
    {
        $dailyIncome = $this->dailyIncomeService->findOrFail($id);
        $dailyIncome = new DailyIncomeResource($dailyIncome);
        $dailyIncome = $dailyIncome->response()->getData(true)['data'];
        return $this->responseFactory->successView(self::VIEW . '.show', $dailyIncome);
    }

    public function update(UpdateDailyIncomeRequest $request, string $id): RedirectResponse
    {
        try {
            $this->dailyIncomeService->update($request->validated(), customDecoder($id));
            return $this->responseFactory->successShowRedirect(self::ROUTE, $id, __(self::LANG_PATH . '_updated'));

        } catch (\Throwable $e) {
            $this->LogError("DailyIncome update failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

    public function destroy(DeleteDailyIncomeRequest $request): RedirectResponse
    {
        try {
            $this->dailyIncomeService->delete($request->validated()['id']);
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_deleted'));
        } catch (\Throwable $e) {
            $this->LogError("DailyIncome destroy failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }
}
