<?php

namespace BasicDashboard\Mobile\OwnProducts\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Storage;

/**
 *
 * A OwnProductResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class OwnProductResource extends JsonResource
{
    public function toArray($request):array
    {
        $imageCloudPhoto = $this->image ?: config('cache.default_profile_photo_cloud');
        $imageLocalPhoto = $this->image ?: config('cache.default_profile_photo_local');
        $image = config('cache.file_system_disk') == 'local' ? $imageLocalPhoto : Storage::url($imageCloudPhoto);
         return [
            "id" =>customEncoder($this->id),
            "name"=>$this->name,
            "unit_id"=>$this->unit_id,
            "category_id"=>$this->category_id,
            "unit"=>$this->unit?->name,
            "category"=>$this->category?->name,
            "price" => number_format($this->price, 0, '.', ','),
            "investment" => number_format($this->investment, 0, '.', ','),
            "profit" => number_format($this->profit, 0, '.', ','),
            "image"=> $image,
            "created_at" => $this->created_at,
        ];
    }
}
