<?php

namespace BasicDashboard\Web\Audits\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A AuditResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuditResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            "id"             => customEncoder($this->id),
            "auditable_type" => $this->model,
            "event"          => $this->event,
            "old_data"       => json_encode(json_decode($this->old_data), JSON_PRETTY_PRINT),
            "new_data"       => json_encode(json_decode($this->new_data), JSON_PRETTY_PRINT),
            "user_name"      => $this->user?->name ?? $this->user?->fullname ?? '---',
            "ip_address"     => "---",
            "created_at"     => $this->created_at,
        ];
    }
}
