<?php

namespace BasicDashboard\Web\Audits\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A AuditResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuditResource extends JsonResource
{
    public function toArray($request): array
    {
        $oldData = json_decode($this->old_data, true) ?: [];
        $newData = json_decode($this->new_data, true) ?: [];
        $auditableId = $newData['id'] ?? $oldData['id'] ?? '---';

        return [
            "id"             => customEncoder($this->id),
            "auditable_type" => $this->model,
            "auditable_id"   => $auditableId,
            "event"          => $this->event,
            "old_values"     => $this->old_data,
            "new_values"     => $this->new_data,
            "user_name"      => $this->user?->name ?? $this->user?->fullname ?? '---',
            "ip_address"     => "---",
            "user_agent"     => "---",
            "created_at"     => $this->created_at,
        ];
    }
}
