<?php

namespace BasicDashboard\Mobile\Users\Resources;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A UserResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UserResource extends JsonResource
{
    public function toArray($request): array
    {

        $avatarPhoto = $this->avatar ?: "/Default/default_profile_photo.jpg";
        return [
            'fullname' => $this->fullname,
            'phone_number' => $this->phone_number,
            "email" => $this->email,
            "avatar" => Storage::url($avatarPhoto),
        ];
    }
}
