<?php

namespace BasicDashboard\Web\Audits\Controllers;

use BasicDashboard\Foundations\Shared\BaseCrudController;
use BasicDashboard\Web\Audits\Services\AuditService;
use BasicDashboard\Web\Audits\Resources\AuditResource;
use Illuminate\Routing\ResponseFactory;

/**
 *
 * A AuditController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 */

class AuditController extends BaseCrudController
{
    protected string $viewPath = 'admin.audit';
    protected string $routePrefix = 'audits';
    protected string $langPath = "audit.audit";
    protected string $resourceClass = AuditResource::class;

    public function __construct(
        protected AuditService $auditService,
        protected ResponseFactory $responseFactory
    ) {
        parent::__construct($responseFactory);
        $this->service = $auditService;
    }
}
