<?php

namespace BasicDashboard\Web\Audits\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Audits\Services\AuditService;
use BasicDashboard\Web\Audits\Resources\AuditResource;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;
use Throwable;

/**
 *
 * A AuditController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 */

class AuditController extends BaseController
{
    const VIEW = 'admin.audit';
    const ROUTE = 'audits';
    const LANG_PATH = "audit.audit";

    public function __construct(
        private AuditService $auditService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function index(Request $request): View
    {
        $auditList = $this->auditService->paginate($request->all());
        $auditList = AuditResource::collection($auditList)->response()->getData(true);
        return $this->responseFactory->successView(self::VIEW . '.index', $auditList);
    }

    public function show(string $id): View | RedirectResponse
    {
        try {
            $decodedId = customDecoder($id);
            $audit = $this->auditService->findOrFail($decodedId);
            $audit = new AuditResource($audit);
            $audit = $audit->response()->getData(true)['data'];
            return $this->responseFactory->successView(self::VIEW . '.show', $audit);
        } catch (Throwable $e) {
            $this->LogError("Audit show failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }
}
