<?php

namespace BasicDashboard\Web\Audits\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Audits\Services\AuditService;
use BasicDashboard\Web\Audits\Resources\AuditResource;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Inertia\Inertia;
use Inertia\Response;
use Throwable;

/**
 *
 * A AuditController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 */

class AuditController extends BaseController
{
    const VIEW = 'admin.audit';
    const ROUTE = 'audits';
    const LANG_PATH = "audit.audit";

    public function __construct(
        private AuditService $auditService
    ) {
    }

    public function index(Request $request): Response
    {
        $auditList = $this->auditService->paginate($request->all());
        $auditList = AuditResource::collection($auditList)->response()->getData(true);
        return Inertia::render('Audits/Index', $auditList);
    }

    public function show(string $id): Response | RedirectResponse
    {
        try {
            $decodedId = customDecoder($id);
            $audit = $this->auditService->findOrFail($decodedId);
            $audit = new AuditResource($audit);
            $audit = $audit->response()->getData(true)['data'];
            return Inertia::render('Audits/Show', [
                'audit' => $audit
            ]);
        } catch (Throwable $e) {
            $this->LogError("Audit show failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }
}
