<?php

namespace BasicDashboard\Mobile\OwnProduct\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Mobile\OwnProduct\Services\OwnProductService;
use BasicDashboard\Mobile\OwnProduct\Resources\OwnProductResource;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\ResponseFactory;
use Throwable;




/**
 *
 * A OwnProductController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * @tags Mobile
 *
 */

class OwnProductController extends Controller
{
    public function __construct(
        private OwnProductService $ownProductService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function index(Request $request): JsonResponse
    {
        try {
            $ownProductList = $this->ownProductService->paginate($request->all());
            $ownProductList = OwnProductResource::collection($ownProductList)->response()->getData(true);
            return $this->responseFactory->sendSuccessResponse('Index Success', $ownProductList);
        } catch (Throwable $e) {
            return $this->responseFactory->sendErrorResponse($e->getMessage());
        }
    }

    public function show(string $id): JsonResponse
    {
        try {
            $ownProduct = $this->ownProductService->findOrFail($id);
            $ownProduct = new OwnProductResource($ownProduct);
            $ownProductData = $ownProduct->response()->getData(true)['data'];
            return $this->responseFactory->sendSuccessResponse("Show success", $ownProductData);
        } catch (Throwable $e) {
            return $this->responseFactory->sendErrorResponse($e->getMessage());
        }
    }
}
