<?php

namespace BasicDashboard\Mobile\OwnProduct\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Mobile\OwnProduct\Services\OwnProductService;
use BasicDashboard\Mobile\OwnProduct\Resources\OwnProductResource;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\ResponseFactory;




/**
 *
 * A OwnProductController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * @tags Mobile
 *
 */

class OwnProductController extends Controller
{
    public function __construct(
        private OwnProductService $ownProductService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function index(Request $request): JsonResponse
    {
        $ownProductList = $this->ownProductService->paginate($request->all());
        $ownProductList = OwnProductResource::collection($ownProductList)->response()->getData(true);
        return $this->responseFactory->sendSuccessResponse('Index Success', $ownProductList);
    }

    public function show(string $id): JsonResponse
    {
        $ownProduct = $this->ownProductService->findOrFail($id);
        $ownProduct = new OwnProductResource($ownProduct);
        $ownProduct = $ownProduct->response()->getData(true)['data'];
        return $this->responseFactory->sendSuccessResponse("Show success", $ownProduct);
    }
}
