<?php

namespace BasicDashboard\Mobile\Categories\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Mobile\Categories\Services\CategoryService;
use BasicDashboard\Mobile\Categories\Resources\CategoryResource;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\ResponseFactory;
use Throwable;

/**
 *
 * A CategoryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * @tags Mobile
 *
 */

class CategoryController extends Controller
{
    public function __construct(
        private CategoryService $categoryService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function index(Request $request): JsonResponse
    {
        try {
            $categoryList = $this->categoryService->paginate($request->all());
            $categoryList = CategoryResource::collection($categoryList)->response()->getData(true);
            return $this->responseFactory->sendSuccessResponse('Index Success', $categoryList);
        } catch (Throwable $e) {
            return $this->responseFactory->sendErrorResponse($e->getMessage());
        }
    }


    public function show(string $id): JsonResponse
    {
        try {
            $category = $this->categoryService->findOrFail($id);
            $category = new CategoryResource($category);
            $categoryData = $category->response()->getData(true)['data'];
            return $this->responseFactory->sendSuccessResponse("Show success", $categoryData);
        } catch (Throwable $e) {
            return $this->responseFactory->sendErrorResponse($e->getMessage());
        }
    }

}
