<?php

namespace BasicDashboard\Web\Roles\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Roles\Services\RoleService;
use BasicDashboard\Web\Roles\Validation\StoreRoleRequest;
use BasicDashboard\Web\Roles\Validation\UpdateRoleRequest;
use BasicDashboard\Web\Roles\Validation\DeleteRoleRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 *
 * A RoleController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class RoleController extends BaseController
{
    public function __construct(
        private RoleService $roleService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->roleService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return $this->roleService->create();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store(StoreRoleRequest $request): RedirectResponse
    {
        return $this->roleService->store($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        return $this->roleService->edit($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        return $this->roleService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update(UpdateRoleRequest $request, string $id): RedirectResponse
    {
        return $this->roleService->update($request->validated(), $id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy(DeleteRoleRequest $request): RedirectResponse
    {
        return $this->roleService->destroy($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
