<?php

namespace BasicDashboard\Web\Roles\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Roles\Services\RoleService;
use BasicDashboard\Web\Roles\Validation\StoreRoleRequest;
use BasicDashboard\Web\Roles\Validation\UpdateRoleRequest;
use BasicDashboard\Web\Roles\Validation\DeleteRoleRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;
use BasicDashboard\Web\Roles\Resources\RoleResource;
use Throwable;

/**
 *
 * A RoleController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class RoleController extends BaseController
{
    const VIEW = 'admin.role';
    const ROUTE = 'roles';
    const LANG_PATH = "role.role";

    public function __construct(
        private RoleService $roleService,
        private ResponseFactory $responseFactory
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        $roleList = $this->roleService->paginate($request->all());
        $roleList = RoleResource::collection($roleList)->response()->getData(true);
        return $this->responseFactory->successView(self::VIEW . '.index', $roleList);
    }

    public function create(): View
    {
        $getAllPermissions = $this->roleService->getFormattedPermissions();
        return view(self::VIEW . '.create', compact('getAllPermissions'));
    }

    public function store(StoreRoleRequest $request): RedirectResponse
    {
        try {
            $this->roleService->store($request->validated());
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_created'));
        } catch (Throwable $e) {
            $this->LogError("Role store failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

    public function edit(string $id): View | RedirectResponse
    {
        $decodedId = customDecoder($id);
        $data = $this->roleService->findOrFail($decodedId);      
        $role = new RoleResource($data['role']);
        $role = $role->response()->getData(true)['data'];
        $data['role'] = $role;
        return $this->responseFactory->successView(self::VIEW . ".edit", $data);        
    }

    public function show(string $id): View | RedirectResponse
    {
        $decodedId = customDecoder($id);
        $data = $this->roleService->findOrFail($decodedId);
        $role = new RoleResource($data['role']);
        $role = $role->response()->getData(true)['data'];
        $data['role'] = $role;
        return $this->responseFactory->successView(self::VIEW . '.show', $data);
    }

    public function update(UpdateRoleRequest $request, string $id): RedirectResponse
    {
        try {
            $this->roleService->update($request->validated(), customDecoder($id));
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_updated'));
        } catch (Throwable $e) {
            $this->LogError("Role update failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

    public function destroy(DeleteRoleRequest $request): RedirectResponse
    {
        try {
            $this->roleService->delete(customDecoder($request->validated()['id']));
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_deleted'));
        } catch (Throwable $e) {
            $this->LogError("Role destroy failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
