<?php

namespace BasicDashboard\Web\Roles\Controllers;

use App\Exceptions\WarningException;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Roles\Resources\RoleResource;
use BasicDashboard\Web\Roles\Services\RoleService;
use BasicDashboard\Web\Roles\Validation\StoreRoleRequest;
use BasicDashboard\Web\Roles\Validation\UpdateRoleRequest;
use BasicDashboard\Web\Roles\Validation\DeleteRoleRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Inertia\Inertia;
use Inertia\Response;
use Throwable;
use BasicDashboard\Foundations\Domain\Roles\Role;

/**
 *
 * A RoleController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class RoleController extends BaseController
{
    const VIEW = 'admin.role';
    const ROUTE = 'roles';
    const LANG_PATH = "role.role";

    public function __construct(
        private RoleService $roleService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): Response
    {
        $roleList = $this->roleService->paginate($request->all());
        $roleList = RoleResource::collection($roleList)->response()->getData(true);
        return Inertia::render('Roles/Index', $roleList);
    }

    public function create(): Response
    {
        $getAllPermissions = $this->roleService->getFormattedPermissions();
        return Inertia::render('Roles/CreateEdit', [
            'getAllPermissions' => $getAllPermissions,
            'getCurrentPermissions' => []
        ]);
    }

    public function store(StoreRoleRequest $request): RedirectResponse
    {
        try {
            $this->roleService->store($request->validated());
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_created'));
        } catch (Throwable $e) {
            $this->LogError("Role store failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function edit(Role $role): Response
    {
        $data = $this->roleService->findOrFail($role->id);      
        $roleResource = new RoleResource($data['role']);
        $data['role'] = $roleResource->resolve();
        return Inertia::render('Roles/CreateEdit', $data);        
    }

    public function show(Role $role): Response
    {
        $data = $this->roleService->findOrFail($role->id);
        $roleResource = new RoleResource($data['role']);
        $data['role'] = $roleResource->resolve();
        return Inertia::render('Roles/Show', $data);
    }

    public function update(UpdateRoleRequest $request, Role $role): RedirectResponse
    {
        try {
            $this->roleService->update($request->validated(), $role->id);
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_updated'));
        } catch (Throwable $e) {
            $this->LogError("Role update failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function destroy(DeleteRoleRequest $request): RedirectResponse
    {
        try {
            $this->roleService->delete(customDecoder($request->validated()['id']));
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_deleted'));
        } catch (WarningException $e) {
            return back()->with('warning', __($e->getMessage()));
        } catch (Throwable $e) {
            $this->LogError("Role destroy failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
