<?php

namespace BasicDashboard\Mobile\OwnProduct\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateOwnProductRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateOwnProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
          "name"=>"required",
        ];
    }
}
