<?php
namespace BasicDashboard\Spa\Users\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Spa\Users\Services\UserService;
use BasicDashboard\Spa\Users\Validation\ShowUserRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 *
 * A UserController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UserController extends Controller
{
    public function __construct(
        private UserService $userService
    ) {
    }
    public function index(Request $request): JsonResponse
    {
        return $this->userService->index($request->all());
    }


    public function show(string $id): JsonResponse
    {
        return $this->userService->show($id);
    }

}
