<?php
namespace BasicDashboard\Spa\Users\Controllers;

use BasicDashboard\Spa\Common\BaseSpaController;
use BasicDashboard\Spa\Users\Services\UserService;
use BasicDashboard\Spa\Users\Validation\ShowUserRequest;
use Illuminate\Http\JsonResponse;

/**
 *
 * A UserController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UserController extends BaseSpaController
{
    public function __construct(
        private UserService $userService
    ) {
    }
    public function showUser(ShowUserRequest $request): JsonResponse
    {
        return $this->userService->showUser($request->validated());
    }

}
