<?php
namespace BasicDashboard\Spa\Users\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A ShowUserRequest is responsible validation of while showing user.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ShowUserRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "user_id" => "required",
        ];
    }
}
