<?php

namespace BasicDashboard\Spa\Products\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Spa\Products\Services\ProductService;
use BasicDashboard\Spa\Products\Resources\ProductResource;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\ResponseFactory;



/**
 *
 * A ProductController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * @tags Spa
 *
 */

class ProductController extends Controller
{
    public function __construct(
        private ProductService $productService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function index(Request $request): JsonResponse
    {
        $productList = $this->productService->paginate($request->all());
        $productList = ProductResource::collection($productList)->response()->getData(true);
        return $this->responseFactory->sendSuccessResponse('Index Success', $productList);
    }


    public function show(string $id): JsonResponse
    {
        $product = $this->productService->findOrFail($id);
        $product = new ProductResource($product);
        $product = $product->response()->getData(true)['data'];
        return $this->responseFactory->sendSuccessResponse("Show success", $product);
    }

}
