<?php

namespace BasicDashboard\Spa\Products\Controllers;

use App\Http\Controllers\Controller;
use BasicDashboard\Spa\Products\Services\ProductService;
use BasicDashboard\Spa\Products\Resources\ProductResource;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\ResponseFactory;



/**
 *
 * A ProductController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * @tags Spa
 *
 */

class ProductController extends Controller
{
    public function __construct(
        private ProductService $productService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function fetchHomeData(Request $request): JsonResponse
    {
        $productList = $this->productService->fetchHomeData($request->all());
        $bannerData = ProductResource::collection($productList['bannerData'])->response()->getData(true);
        $miniBannerData = ProductResource::collection($productList['miniBannerData'])->response()->getData(true);
        $normalData = ProductResource::collection($productList['normalData'])->response()->getData(true);
        $normalDataTwo = ProductResource::collection($productList['normalDataTwo'])->response()->getData(true);
        return $this->responseFactory->sendSuccessResponse('Index Success', [
            'banner_data' => $bannerData['data'],
            'mini_banner_data' => $miniBannerData['data'],
            'normal_data' => $normalData['data'],
            'normal_data_two' => $normalDataTwo['data'],
        ]);
    }

    public function index(Request $request): JsonResponse
    {
        $productList = $this->productService->paginate($request->all());
        $productList = ProductResource::collection($productList)->response()->getData(true);
        return $this->responseFactory->sendSuccessResponse('Index Success', $productList);
    }


    public function show(string $id): JsonResponse
    {
        $product = $this->productService->findOrFail($id);
        $product = new ProductResource($product);
        $product = $product->response()->getData(true)['data'];
        return $this->responseFactory->sendSuccessResponse("Show success", $product);
    }

}
