<?php

namespace BasicDashboard\Mobile\Users\Services;

use Exception;
use Illuminate\Http\JsonResponse;
use BasicDashboard\Mobile\Common\BaseMobileController;
use BasicDashboard\Mobile\Users\Resources\UserResource;
use BasicDashboard\Foundations\Domain\Users\Repositories\UserRepository;
use BasicDashboard\Foundations\Domain\Users\Repositories\UserRepositoryInterface;

/**
 *
 * A UserService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UserService extends BaseMobileController
{

    public function __construct(
        private UserRepositoryInterface $userRepositoryInterface,
    )
    {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(string $search): JsonResponse
    {
        $data = $this->userRepositoryInterface->getUsersByFullNameOrPhoneNumber($search,30)->toArray();
        return $this->sendResponse("Index success", $data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): JsonResponse
    {
        $data = $this->userRepositoryInterface->edit($id);
        $data= new UserResource($data);
        $data= $data->response()->getData(true)['data'];
        return $this->sendResponse('Show success',$data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
