<?php

namespace BasicDashboard\Mobile\Users\Services;

use App\Http\Controllers\Controller;
use BasicDashboard\Foundations\Domain\Users\User;
use Illuminate\Http\JsonResponse;
use BasicDashboard\Mobile\Users\Resources\UserResource;
use Illuminate\Routing\ResponseFactory;


/**
 *
 * A UserService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UserService extends Controller
{

    public function __construct(
        private User $user,
        private ResponseFactory $responseFactory
    )
    {
    }

    public function index($request): JsonResponse
    {
        $userList = $this->user
            ->withUserRelations()                                    
            ->filterByKeyword($request['keyword'] ?? null)          
            ->orderByLatest()                                        
            ->paginate($request['paginate'] ?? config('numbers.paginate'));
        $userList = UserResource::collection($userList)->response()->getData(true);
        return $this->responseFactory->sendSuccessResponse('Index Success', $userList);

    }


    public function show(string $id): JsonResponse
    {
        $user = $this->user->findOrFail($id);
        $user = new UserResource($user);
        $user = $user->response()->getData(true)['data'];
        return $this->responseFactory->sendSuccessResponse('Show success',$user);
    }

}
