<?php

namespace BasicDashboard\Spa\Auth\Resources;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A UserResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuthResource extends JsonResource
{
    public function toArray($request): array
    {

        $avatarPhoto = $this->avatar ? asset($this->avatar) : asset("/Default/default_profile_photo.jpg");
        return [
            'id' => customEncoder($this->id),
            'fullname' => $this->fullname,
            "email" => $this->email,
            "avatar" => $avatarPhoto,
        ];
    }
}
