<?php

namespace BasicDashboard\Foundations\Domain\Categories;
use App\Observers\AuditObserver;
use BasicDashboard\Foundations\Domain\OwnProducts\OwnProduct;
use BasicDashboard\Foundations\Domain\Products\Product;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;


/**
 *
 * A Category is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
//if you want to audit this model uncomment below code and import
#[ObservedBy([AuditObserver::class])]
class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected static function newFactory()
    {
        return \Database\Factories\CategoryFactory::new();
    }

      //protected $table = 'table_name';
    protected $fillable = [
        'name',
        'name_other',
        'description',
        'description_other',
        'is_show',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by',
        'updated_by',
        'deleted_by',
    ];

    // ==========================================
    // Query Scopes for Simplified Architecture
    // ==========================================
    // These scopes replace repository methods, allowing direct Eloquent usage in services
    
    /**
     * Scope to filter categories by keyword search
     * Searches in: name
     * 
     * Usage: Category::filterByKeyword($keyword)->get()
     */
    public function scopeFilterByKeyword($query, ?string $keyword)
    {
        if (empty($keyword)) {
            return $query;
        }

        return $query->where('name', 'LIKE', '%' . $keyword . '%');
    }

    /**
     * Scope to order categories by latest activity
     * Orders by created_at or updated_at (whichever is more recent), then by id
     * 
     * Usage: Category::orderByLatest()->get()
     */
    public function scopeOrderByLatest($query)
    {
        return $query->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderBy('id', 'desc');
    }

    public function products()
    {
        return $this->belongsToMany(Product::class, 'category_product');
    }

    public function ownProducts()
    {
        return $this->hasMany(OwnProduct::class);
    }

    public function hasOwnProducts(): bool
    {
        return $this->ownProducts()->exists();
    }


}
