<?php

namespace BasicDashboard\Foundations\Domain\Categories;
use App\Observers\AuditObserver;
use BasicDashboard\Foundations\Domain\OwnProducts\OwnProduct;
use BasicDashboard\Foundations\Domain\Products\Product;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;


/**
 *
 * A Category is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
//if you want to audit this model uncomment below code and import
#[ObservedBy([AuditObserver::class])]
#[Fillable([
    'name',
    'name_other',
    'description',
    'description_other',
    'is_show',
    'created_at',
    'updated_at',
    'deleted_at',
    'created_by',
    'updated_by',
    'deleted_by',
])]
class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected static function newFactory()
    {
        return \Database\Factories\CategoryFactory::new();
    }

      //protected $table = 'table_name';

    // ==========================================
    // Query Scopes for Simplified Architecture
    // ==========================================
    // These scopes replace repository methods, allowing direct Eloquent usage in services
    
    /**
     * Scope to filter categories by keyword search
     */
    public function scopeFilterByKeyword(Builder $query, ?string $keyword): Builder
    {
        return $query->when($keyword, function (Builder $q) use ($keyword) {
            $q->where('name', 'LIKE', '%' . $keyword . '%');
        });
    }

    /**
     * Scope to order categories by latest activity
     */
    public function scopeOrderByLatest(Builder $query): Builder
    {
        return $query->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderByDesc('id');
    }

    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class, 'category_product');
    }

    public function hasProducts(): bool
    {
        return $this->products()->exists();
    }

    public function ownProducts(): HasMany
    {
        return $this->hasMany(OwnProduct::class);
    }

    public function hasOwnProducts(): bool
    {
        return $this->ownProducts()->exists();
    }


}
