<?php

namespace BasicDashboard\Web\DailyIncomes\Services;

use BasicDashboard\Foundations\Domain\DailyIncomes\DailyIncome;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;


/**
 *
 * A DailyIncomeService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DailyIncomeService
{
    public function __construct(
        private DailyIncome $dailyIncome,
    )
    {
    }

    public function paginate(array $request)
    {
        return $this->dailyIncome
            ->with(['ownProduct.unit'])
            ->filterByKeyword($request['keyword'] ?? null)
            ->orderByLatest()
            ->paginate($request['paginate'] ?? config('numbers.paginate'));

    }

    public function store(array $request): void
    {
        DB::transaction(function () use ($request) {
            $isInstant = isset($request['is_instant']) ? (bool) $request['is_instant'] : false;
            $createdBy = Auth::id();
            $date = $request['date'];
            $note = $request['note'] ?? null;

            foreach ($request['own_product_id'] as $index => $productId) {
                $product = \BasicDashboard\Foundations\Domain\OwnProducts\OwnProduct::find($productId);
                
                $this->dailyIncome->create([
                    'date' => $date,
                    'name' => $product->name ?? 'Unknown',
                    'own_product_id' => $productId,
                    'amount' => $request['amount'][$index],
                    'price' => $request['price'][$index],
                    'investment' => $request['investment'][$index],
                    'profit' => $request['profit'][$index],
                    'is_instant' => $isInstant,
                    'note' => $note,
                    'created_by' => $createdBy,
                ]);
            }
        });
    }

    public function findOrFail(string $id): DailyIncome
    {
        return $this->dailyIncome->findOrFail($id);
    }

    public function update(array $request, string $id): DailyIncome
    {
        return DB::transaction(function () use ($request, $id) {
            $request['is_instant'] = isset($request['is_instant']) ? (bool) $request['is_instant'] : false;
            $dailyIncome = $this->dailyIncome->findOrFail($id);
            $dailyIncome->update($request);
            return $dailyIncome;
        });
    }



    public function delete(string $id): void
    {
        DB::transaction(function () use ($id) {
            $dailyIncome = $this->dailyIncome->findOrFail($id);
            $dailyIncome->delete();
        });
    }

}
