<?php

namespace BasicDashboard\Web\OwnProducts\Controllers;

use BasicDashboard\Foundations\Shared\BaseCrudController;
use BasicDashboard\Web\OwnProducts\Resources\OwnProductResource;
use BasicDashboard\Web\OwnProducts\Services\OwnProductService;
use BasicDashboard\Web\OwnProducts\Validation\StoreOwnProductRequest;
use BasicDashboard\Web\OwnProducts\Validation\UpdateOwnProductRequest;
use BasicDashboard\Web\OwnProducts\Validation\DeleteOwnProductRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;

/**
 *
 * A OwnProductController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class OwnProductController extends BaseCrudController
{
    protected string $viewPath = 'admin.own-product';
    protected string $routePrefix = 'own-products';
    protected string $langPath = "ownProduct.ownProduct";
    protected string $resourceClass = OwnProductResource::class;

    public function __construct(
        protected OwnProductService $ownProductService,
        protected ResponseFactory $responseFactory
    ) {
        parent::__construct($responseFactory);
        $this->service = $ownProductService;
    }

    public function store(StoreOwnProductRequest $request): RedirectResponse
    {
        return parent::performStore($request);
    }

    public function update(UpdateOwnProductRequest $request, string $id): RedirectResponse
    {
        return parent::performUpdate($request, $id);
    }

    public function destroy(DeleteOwnProductRequest $request): RedirectResponse
    {
        return parent::performDestroy($request);
    }
}
