<?php

namespace BasicDashboard\Web\OwnProducts\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\OwnProducts\Resources\OwnProductResource;
use BasicDashboard\Web\OwnProducts\Services\OwnProductService;
use BasicDashboard\Web\OwnProducts\Validation\StoreOwnProductRequest;
use BasicDashboard\Web\OwnProducts\Validation\UpdateOwnProductRequest;
use BasicDashboard\Web\OwnProducts\Validation\DeleteOwnProductRequest;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use BasicDashboard\Web\Categories\Services\CategoryService;
use BasicDashboard\Web\Units\Services\UnitService;
use Inertia\Inertia;
use Inertia\Response;
use Throwable;
use App\Exceptions\WarningException;


/**
 *
 * A OwnProductController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class OwnProductController extends BaseController
{
    const VIEW = 'admin.own-product';
    const ROUTE = 'own-products';
    const LANG_PATH = "ownProduct.ownProduct";

    public function __construct(
        private OwnProductService $ownProductService,
        private CategoryService $categoryService,
        private UnitService $unitService,
    ) {
    }

    public function index(Request $request): Response
    {
        $ownProductList = $this->ownProductService->paginate($request->all());
        $ownProductList = OwnProductResource::collection($ownProductList)->response()->getData(true);
        return Inertia::render('OwnProducts/Index', $ownProductList);
    }

    public function create(): Response
    {
        $categories = $this->categoryService->getNotShowCategories();
        $units = $this->unitService->all();
        return Inertia::render('OwnProducts/CreateEdit', [
            'categories' => $categories,
            'units' => $units,
        ]);
    }

    public function store(StoreOwnProductRequest $request): RedirectResponse
    {
        try {
            $this->ownProductService->store($request->validated());
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_created'));
        } catch (Throwable $e) {
            $this->LogError("OwnProduct store failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function edit(string $id): Response
    {
        $decodedId = customDecoder($id);
        $ownProduct = $this->ownProductService->findOrFail($decodedId);
        $ownProduct = new OwnProductResource($ownProduct);
        $ownProduct = $ownProduct->response()->getData(true)['data'];
        
        $categories = app(CategoryService::class)->all();
        $units = app(UnitService::class)->all();

        return Inertia::render('OwnProducts/CreateEdit', [
            'ownProduct' => $ownProduct,
            'categories' => $categories,
            'units' => $units,
        ]);
    }

    public function show(string $id): Response
    {
        $ownProduct = $this->ownProductService->findOrFail($id);
        $ownProduct = new OwnProductResource($ownProduct);
        $ownProduct = $ownProduct->response()->getData(true)['data'];
        return Inertia::render('OwnProducts/CreateEdit', [
            'ownProduct' => $ownProduct,
        ]);
    }

    public function update(UpdateOwnProductRequest $request, string $id): RedirectResponse
    {
        try {
            $this->ownProductService->update($request->validated(), customDecoder($id));
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_updated'));
        } catch (Throwable $e) {
            $this->LogError("OwnProduct update failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function destroy(DeleteOwnProductRequest $request): RedirectResponse
    {
        try {
            $this->ownProductService->delete($request->validated()['id']);
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_deleted'));
        } catch (WarningException $e) {
            return back()->with('error', __($e->getMessage()));
        } catch (Throwable $e) {
            $this->LogError("OwnProduct destroy failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function search(Request $request): \Illuminate\Http\JsonResponse
    {
        $products = $this->ownProductService->paginate([
            'keyword' => $request->get('keyword'),
            'paginate' => 20,
        ]);
        
        $products = OwnProductResource::collection($products);
        
        return response()->json($products->response()->getData(true));
    }
}
