<?php

namespace BasicDashboard\Web\OwnProducts\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\OwnProducts\Resources\OwnProductResource;
use BasicDashboard\Web\OwnProducts\Services\OwnProductService;
use BasicDashboard\Web\OwnProducts\Validation\StoreOwnProductRequest;
use BasicDashboard\Web\OwnProducts\Validation\UpdateOwnProductRequest;
use BasicDashboard\Web\OwnProducts\Validation\DeleteOwnProductRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;


/**
 *
 * A OwnProductController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class OwnProductController extends BaseController
{
    const VIEW = 'admin.own-product';
    const ROUTE = 'own-products';
    const LANG_PATH = "ownProduct.ownProduct";

    public function __construct(
        private OwnProductService $ownProductService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function index(Request $request): View
    {
        $ownProductList = $this->ownProductService->paginate($request->all());
        $ownProductList = OwnProductResource::collection($ownProductList)->response()->getData(true);
        return $this->responseFactory->successView(self::VIEW . '.index', $ownProductList);
    }

    public function create(): View
    {
        return view(self::VIEW . '.create');
    }

    public function store(StoreOwnProductRequest $request): RedirectResponse
    {
        try {
            $this->ownProductService->store($request->validated());
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_created'));
        } catch (\Throwable $e) {
            $this->LogError("OwnProduct store failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

    public function edit(string $id): View | RedirectResponse
    {
        $decodedId = customDecoder($id);
        $ownProduct = $this->ownProductService->findOrFail($decodedId);
        $ownProduct = new OwnProductResource($ownProduct);
        $ownProduct = $ownProduct->response()->getData(true)['data'];
        return $this->responseFactory->successView(self::VIEW . ".edit", $ownProduct);
    }

    public function show(string $id): View | RedirectResponse
    {
        $ownProduct = $this->ownProductService->findOrFail($id);
        $ownProduct = new OwnProductResource($ownProduct);
        $ownProduct = $ownProduct->response()->getData(true)['data'];
        return $this->responseFactory->successView(self::VIEW . '.show', $ownProduct);
    }

    public function update(UpdateOwnProductRequest $request, string $id): RedirectResponse
    {
        try {
            $this->ownProductService->update($request->validated(), customDecoder($id));
            return $this->responseFactory->successShowRedirect(self::ROUTE, $id, __(self::LANG_PATH . '_updated'));
        } catch (\Throwable $e) {
            $this->LogError("OwnProduct update failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

    public function destroy(DeleteOwnProductRequest $request): RedirectResponse
    {
        try {
            $this->ownProductService->delete($request->validated()['id']);
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_deleted'));
        } catch (\Throwable $e) {
            $this->LogError("OwnProduct destroy failed", $e);
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }
}
