<?php

namespace BasicDashboard\Mobile\Categories\Services;

use BasicDashboard\Foundations\Domain\Categories\Category;
use BasicDashboard\Mobile\Categories\Resources\CategoryResource;

/**
 *
 * A CategoryService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CategoryService
{

    public function __construct(
        private Category $category
    )
    {
    }

    public function paginate(array $request)
    {
        return $this->category
            ->filterByKeyword($request['keyword'] ?? null)
            ->orderByLatest()
            ->where('is_show',false)
            ->paginate($request['paginate'] ?? config('numbers.paginate'));
    }

    public function findOrFail(string $id): Category
    {
        return $this->category->findOrFail($id);
    }
}
