<?php

namespace BasicDashboard\Spa\Categories\Services;

use BasicDashboard\Foundations\Domain\Categories\Category;
use App\Http\Controllers\Controller;
use BasicDashboard\Spa\Categories\Resources\CategoryResource;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Routing\ResponseFactory;

/**
 *
 * A CategoryService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CategoryService extends Controller
{

    public function __construct(
        private Category $category,
        private ResponseFactory $responseFactory,
    )
    {
    }

    public function index(array $request): JsonResponse
    {
        $categoryList = $this->category
            ->filterByKeyword($request['keyword'] ?? null)
            ->orderByLatest()
            ->paginate($request['paginate'] ?? config('numbers.paginate'));
        $categoryList = CategoryResource::collection($categoryList)->response()->getData(true);
        return $this->responseFactory->sendSuccessResponse('Index Success', $categoryList);
    }

    public function show(string $id): JsonResponse
    {
        $data = $this->category->findOrFail($id);
        $data = new CategoryResource($data);
        $data = $data->response()->getData(true)['data'];
        return $this->responseFactory->sendSuccessResponse("Show success", $data);
    }

    public function fetchAll(): JsonResponse
    {
        $data = $this->category->get(['id','name','name_other']);
        $data = CategoryResource::collection($data)->response()->getData(true)['data'];
        return $this->responseFactory->sendSuccessResponse("Fetch All success", $data);
    }
}
