<?php

namespace BasicDashboard\Mobile\DailyIncomes\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreDailyIncomeRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreDailyIncomeRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        if (!$this->has('items') && $this->has('own_product_id')) {
            $items = [];
            foreach ($this->input('own_product_id') as $index => $productId) {
                $items[] = [
                    'product_id' => $productId,
                    'amount' => $this->input('amount')[$index] ?? 0,
                    'unit_id' => $this->input('unit_id')[$index] ?? null,
                    'price' => $this->input('price')[$index] ?? 0,
                    'investment' => $this->input('investment')[$index] ?? 0,
                    'profit' => $this->input('profit')[$index] ?? 0,
                ];
            }
            $this->merge(['items' => $items]);
        }

        $this->merge([
            'is_instant' => $this->boolean('is_instant') ? 1 : 0,
        ]);
    }

    public function rules(): array
    {
        return [
            "date" => "required|date",
            "items" => "required|array|min:1",
            "items.*.product_id" => "required|exists:own_products,id",
            "items.*.amount" => "required|numeric|min:0.01",
            "items.*.unit_id" => "required|exists:units,id",
            "items.*.price" => "required|numeric",
            "items.*.investment" => "required|numeric",
            "items.*.profit" => "required|numeric",
            "is_instant" => "nullable|boolean",
            "note" => "nullable|string",
        ];
    }

    public function messages(): array
    {
        return [
            "date.required" => "Date is required",
            "items.required" => "Items are required",
            "items.*.product_id.required" => "Product selection is required",
            "items.*.amount.required" => "Amount is required",
            "items.*.unit_id.required" => "Unit is required",
            "items.*.price.required" => "Price is required",
            "items.*.investment.required" => "Investment is required",
            "items.*.profit.required" => "Profit is required",
        ];
    }
}
