<?php

namespace BasicDashboard\Web\Units\Services;

use BasicDashboard\Foundations\Domain\Units\Unit;
use BasicDashboard\Foundations\Shared\BaseCrudService;

/**
 *
 * A UnitService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UnitService extends BaseCrudService
{
    public function __construct(Unit $unit)
    {
        parent::__construct($unit);
    }
}
