<?php

namespace BasicDashboard\Web\DailyIncomes\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A DailyIncomeResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DailyIncomeResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" =>customEncoder($this->id),
            "date"=>$this->date,
            "name"=>$this->name,
            "own_product_id"=>$this->own_product_id,
            "own_product"=>$this->ownProduct?->name,
            "amount" => number_format($this->amount, 0, '.', ','),
            "price" => number_format($this->price, 0, '.', ','),
            "investment" => number_format($this->investment, 0, '.', ','),
            "profit" => number_format($this->profit, 0, '.', ','),
            "unit"=>$this->ownProduct?->unit?->name,
            "unit_id"=>$this->ownProduct?->unit?->id,
            "is_instant" => $this->dailyIncomeTotal?->is_instant ?? true,
            "voucher_no" => $this->dailyIncomeTotal?->voucher_no,
            "note" => $this->dailyIncomeTotal?->note,

        ];
    }
}
