<?php

namespace BasicDashboard\Web\DailyIncomes\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A DailyIncomeResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DailyIncomeResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" =>customEncoder($this->id),
            "date"=>$this->date,
            "name"=>$this->name,
            "own_product_id"=>$this->own_product_id,
            "own_product"=>$this->ownProduct?->name,
            "amount"=>$this->amount,
            "price"=>$this->price,
            "investment"=>$this->investment,
            "profit"=>$this->profit,
            "unit"=>$this->ownProduct?->Unit?->name,
            "unit_id"=>$this->ownProduct?->Unit?->id,
            "is_instant"=>$this->is_instant,
            "note"=>$this->note,

        ];
    }
}
