<?php

namespace BasicDashboard\Web\Categories\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Categories\Services\CategoryService;
use BasicDashboard\Web\Categories\Validation\StoreCategoryRequest;
use BasicDashboard\Web\Categories\Validation\UpdateCategoryRequest;
use BasicDashboard\Web\Categories\Validation\DeleteCategoryRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 *
 * A CategoryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CategoryController extends BaseController
{
    public function __construct(
        private CategoryService $categoryService
    ) {
    }

    public function index(Request $request): View
    {
        return $this->categoryService->index($request->all());
    }

    public function create(): View
    {
        return $this->categoryService->create();
    }

    public function store(StoreCategoryRequest $request): RedirectResponse
    {
        return $this->categoryService->store($request->all());
    }

    public function edit(string $id): View | RedirectResponse
    {
        return $this->categoryService->edit($id);
    }

    public function show(string $id): View | RedirectResponse
    {
        return $this->categoryService->show($id);
    }

    public function update(UpdateCategoryRequest $request, string $id): RedirectResponse
    {
        return $this->categoryService->update($request->all(), $id);
    }

    public function destroy(DeleteCategoryRequest $request): RedirectResponse
    {
        return $this->categoryService->destroy($request->validated());
    }

}
