<?php

namespace BasicDashboard\Web\Categories\Controllers;

use BasicDashboard\Web\Categories\Resources\CategoryResource;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Categories\Services\CategoryService;
use BasicDashboard\Web\Categories\Validation\StoreCategoryRequest;
use BasicDashboard\Web\Categories\Validation\UpdateCategoryRequest;
use BasicDashboard\Web\Categories\Validation\DeleteCategoryRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;
use App\Exceptions\WarningException;
use Throwable;


/**
 *
 * A CategoryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

use Inertia\Inertia;
use Inertia\Response;

class CategoryController extends BaseController
{
    const VIEW = 'Categories/Index';
    const ROUTE = 'categories';
    const LANG_PATH = "category.category";

    public function __construct(
        private CategoryService $categoryService,
        private ResponseFactory $responseFactory
    ) {
    }

    public function index(Request $request): Response
    {
        $categoryList = $this->categoryService->paginate($request->all() ?? []);
        $categoryList = CategoryResource::collection($categoryList)->response()->getData(true);
        return Inertia::render(self::VIEW, $categoryList);
    }

    public function store(StoreCategoryRequest $request): RedirectResponse
    {
        try {
            $this->categoryService->store($request->validated());
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_created'));
        } catch (Throwable $e) {
            $this->LogError("Category store failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function update(UpdateCategoryRequest $request, string $id): RedirectResponse
    {
        try {
            $decodedId = customDecoder($id);
            $this->categoryService->update($request->validated(), $decodedId);
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_updated'));
        } catch (Throwable $e) {
            $this->LogError("Category update failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function destroy(DeleteCategoryRequest $request): RedirectResponse
    {
        try {
            $this->categoryService->delete($request->validated()['id']);
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_deleted'));
        } catch (WarningException $e) {
            return back()->with('error', __($e->getMessage()));
        } catch (Throwable $e) {
            $this->LogError("Category destroy failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

}
