<?php

namespace BasicDashboard\Web\Categories\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreCategoryRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreCategoryRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'is_show' => $this->has('is_show') ? 1 : 0,
        ]);
    }

    public function rules(): array
    {
        return [
            "name"=>"required",
            "name_other"=>"required",
            "is_show"=>"nullable|boolean",
            "description"=>"nullable",
            "description_other"=>"nullable",
        ];
    }


    public function messages(): array
    {
        return [
            "name.required" => "Name is required",
            "name_other.required" => "Name Other is required",
        ];
    }
}
