<?php

namespace BasicDashboard\Web\Categories\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateCategoryRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateCategoryRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
          "name"=>"required",
          "name_other"=>"required",
          "description"=>"nullable",
          "description_other"=>"nullable",
        ];
    }

    public function messages(): array
    {
        return [
            "name.required" => "Name is required",
            "name_other.required" => "Name Other is required",
        ];
    }
}
