<?php

namespace BasicDashboard\Web\Units\Controllers;

use BasicDashboard\Foundations\Shared\BaseCrudController;
use BasicDashboard\Web\Units\Resources\UnitResource;
use BasicDashboard\Web\Units\Services\UnitService;
use BasicDashboard\Web\Units\Validation\StoreUnitRequest;
use BasicDashboard\Web\Units\Validation\UpdateUnitRequest;
use BasicDashboard\Web\Units\Validation\DeleteUnitRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;

/**
 *
 * A UnitController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UnitController extends BaseCrudController
{
    protected string $viewPath = 'admin.unit';
    protected string $routePrefix = 'units';
    protected string $langPath = "unit.unit";
    protected string $resourceClass = UnitResource::class;

    public function __construct(
        protected UnitService $unitService,
        protected ResponseFactory $responseFactory
    ) {
        parent::__construct($responseFactory);
        $this->service = $unitService;
    }

    public function store(StoreUnitRequest $request): RedirectResponse
    {
        return parent::performStore($request);
    }

    public function update(UpdateUnitRequest $request, string $id): RedirectResponse
    {
        return parent::performUpdate($request, $id);
    }

    public function destroy(DeleteUnitRequest $request): RedirectResponse
    {
        return parent::performDestroy($request);
    }
}
