<?php

namespace BasicDashboard\Web\Units\Controllers;

use App\Exceptions\WarningException;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Units\Resources\UnitResource;
use BasicDashboard\Web\Units\Services\UnitService;
use BasicDashboard\Web\Units\Validation\StoreUnitRequest;
use BasicDashboard\Web\Units\Validation\UpdateUnitRequest;
use BasicDashboard\Web\Units\Validation\DeleteUnitRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Inertia\Inertia;
use Inertia\Response;
use Throwable;


/**
 *
 * A UnitController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UnitController extends BaseController
{
    const VIEW = 'admin.unit';
    const ROUTE = 'units';
    const LANG_PATH = "unit.unit";

    public function __construct(
        private UnitService $unitService
    ) {
    }

    public function index(Request $request): Response
    {
        $unitList = $this->unitService->paginate($request->all());
        $unitList = UnitResource::collection($unitList)->response()->getData(true);
        return Inertia::render('Units/Index', $unitList);
    }

    public function create(): Response
    {
        return Inertia::render('Units/CreateEdit');
    }

    public function store(StoreUnitRequest $request): RedirectResponse
    {
        try {
            $this->unitService->store($request->validated());
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_created'));
        } catch (Throwable $e) {
            $this->LogError("Unit store failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function edit(string $id): Response
    {
        $decodedId = customDecoder($id);
        $unit = $this->unitService->findOrFail($decodedId);
        $unit = new UnitResource($unit);
        $unit = $unit->response()->getData(true)['data'];
        return Inertia::render('Units/CreateEdit', [
            'unit' => $unit
        ]);
    }

    public function show(string $id): Response
    {
        $unit = $this->unitService->findOrFail($id);
        $unit = new UnitResource($unit);
        $unit = $unit->response()->getData(true)['data'];
        return Inertia::render('Units/Show', [
            'unit' => $unit
        ]);
    }

    public function update(UpdateUnitRequest $request, string $id): RedirectResponse
    {
        try {
            $this->unitService->update($request->validated(), $id);
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_updated'));
        } catch (Throwable $e) {
            $this->LogError("Unit update failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }

    public function destroy(DeleteUnitRequest $request): RedirectResponse
    {
        try {
            $this->unitService->delete($request->validated()['id']);
            return redirect()->route(self::ROUTE . '.index')->with('success', __(self::LANG_PATH . '_deleted'));
        } catch (WarningException $e) {
            return back()->with('warning', __($e->getMessage()));
        } catch (Throwable $e) {
            $this->LogError("Unit destroy failed", $e);
            return back()->with('error', $e->getMessage());
        }
    }
}
