<?php

namespace BasicDashboard\Mobile\OwnProducts\Services;

use BasicDashboard\Foundations\Domain\OwnProducts\OwnProduct;
/**
 *
 * A OwnProductService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class OwnProductService
{
    public function __construct(
        private OwnProduct $ownProduct,
    )
    {
    }

    public function paginate(array $request)
    {
        return $this->ownProduct
            ->filterByKeyword($request['keyword'] ?? null)
            ->orderByLatest()
            ->paginate($request['paginate'] ?? config('numbers.paginate'));
    }

    public function findOrFail(string $id): OwnProduct
    {
        return $this->ownProduct->findOrFail($id);
    }
}
