<?php

namespace BasicDashboard\Web\OwnProducts\Services;

use BasicDashboard\Foundations\Domain\OwnProducts\OwnProduct;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\OwnProducts\Resources\OwnProductResource;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;
use Exception;

/**
 *
 * A OwnProductService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class OwnProductService
{
    public function __construct(
        private OwnProduct $ownProduct,
    )
    {
    }

    public function paginate(array $request)
    {
        return $this->ownProduct
            ->with(['unit', 'category'])
            ->filterByKeyword($request['keyword'] ?? null)
            ->orderByLatest()
            ->paginate($request['paginate'] ?? config('numbers.paginate'));

    }

    public function store(array $request): OwnProduct
    {
        return \DB::transaction(function () use ($request) {
            $request['created_by'] = Auth::id();
            return $this->ownProduct->create($request);
        });
    }

    public function findOrFail(string $id): OwnProduct
    {
        return $this->ownProduct->findOrFail($id);
    }

    public function update(array $request, string $id): OwnProduct
    {
        return \DB::transaction(function () use ($request, $id) {
            $ownProduct = $this->ownProduct->findOrFail($id);
            $request['updated_by'] = Auth::id();
            $ownProduct->update($request);
            return $ownProduct;
        });
    }

    public function delete(string $id): void
    {
        \DB::transaction(function () use ($id) {
            $ownProduct = $this->ownProduct->findOrFail($id);
            $ownProduct->delete();
        });
    }

}
