<?php

namespace BasicDashboard\Web\OwnProducts\Services;

use BasicDashboard\Foundations\Actions\WebFileStoreAction;
use BasicDashboard\Foundations\Domain\OwnProducts\OwnProduct;
use BasicDashboard\Foundations\Shared\BaseCrudService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

/**
 *
 * A OwnProductService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class OwnProductService extends BaseCrudService
{
    const ROOT = "OwnProducts";

    public function __construct(
        OwnProduct $ownProduct,
        private WebFileStoreAction $webFileStoreAction,
    ) {
        parent::__construct($ownProduct);
    }

    public function paginate(array $request): LengthAwarePaginator
    {
        return $this->model
            ->with(['unit', 'category'])
            ->filterByKeyword($request['keyword'] ?? null)
            ->orderByLatest()
            ->paginate($request['paginate'] ?? config('numbers.paginate'));
    }

    public function store(array $request): Model
    {
        return DB::transaction(function () use ($request) {
            $image   = $request['image'] ?? null;
            $payload = Arr::except($request, ['image']);
            
            $ownProduct = parent::store($payload);

            if ($image) {
                $fileData = $this->webFileStoreAction->store($ownProduct, $image, self::ROOT, 'image');
                $ownProduct->forceFill($fileData)->save();
            }

            return $ownProduct;
        });
    }

    public function update(array $request, string $id): Model
    {
        return DB::transaction(function () use ($request, $id) {
            $image   = $request['image'] ?? null;
            $payload = Arr::except($request, ['image']);

            $ownProduct = parent::update($payload, $id);

            if ($image) {
                $fileData = $this->webFileStoreAction->update($ownProduct, $image, config('cache.file_system_disk'), 'image', self::ROOT);
                $ownProduct->forceFill($fileData)->save();
            }

            return $ownProduct;
        });
    }

    public function delete(string $id): void
    {
        DB::transaction(function () use ($id) {
            $ownProduct = $this->findOrFail($id);
            $this->webFileStoreAction->delete($ownProduct, config('cache.file_system_disk'), 'image');
            parent::delete($id);
        });
    }
}
