<?php

namespace BasicDashboard\Web\Audits\Services;

use BasicDashboard\Foundations\Domain\Audits\Audit;
/**
 *
 * A AuditService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuditService 
{
    public function __construct(
        private Audit $audit
    )
    {
    }

    public function paginate(array $request)
    {
        return $this->audit
            ->filterByKeyword($request['keyword'] ?? null)
            ->with(['user'])
            ->orderByLatest()
            ->paginate($request['paginate'] ?? config('numbers.paginate'));
    }

    public function findOrFail(string $decodedId): Audit
    {
        return $this->audit->with(['user'])->findOrFail($decodedId);
    }
}
