<?php

namespace BasicDashboard\Web\Audits\Services;

use BasicDashboard\Foundations\Domain\Audits\Audit;
use BasicDashboard\Foundations\Shared\BaseCrudService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A AuditService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuditService extends BaseCrudService
{
    protected bool $useDecoder = true;

    public function __construct(Audit $audit)
    {
        parent::__construct($audit);
    }

    public function paginate(array $request): LengthAwarePaginator
    {
        return $this->model
            ->filterByKeyword($request['keyword'] ?? null)
            ->with(['user'])
            ->orderByLatest()
            ->paginate($request['paginate'] ?? config('numbers.paginate'));
    }

    public function findOrFail(string $id): Model
    {
        $resolvedId = $this->useDecoder ? customDecoder($id) : $id;
        return $this->model->with(['user'])->findOrFail($resolvedId);
    }
}
