<?php

namespace BasicDashboard\Web\DailyIncomes\Actions;
use Illuminate\Support\Facades\Auth;


/**
 *
 * A DailyIncomeTrait is the small chunks of service.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DailyIncomeAction
{
    //Store Section
    public function calculateTotalsAndRows(array $request): array
    {
        $createdBy = Auth::id();
        $date = $request['date'];
        $now = now();

        $totalPrice = 0;
        $totalInvestment = 0;
        $totalProfit = 0;

        $rows = [];

        foreach ($request['items'] as $item) {

            $amount = $this->toFloat($item['amount']);
            $price = $this->toFloat($item['price']);
            $investment = $this->toFloat($item['investment']);
            $profit = $this->toFloat($item['profit']);

            $totalPrice += $price;
            $totalInvestment += $investment;
            $totalProfit += $profit;

            $rows[] = [
                'date' => $date,
                'own_product_id' => $item['product_id'],
                'amount' => $amount,
                'price' => $price,
                'investment' => $investment,
                'profit' => $profit,
                'created_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        return [
            'total_price' => $totalPrice,
            'total_investment' => $totalInvestment,
            'total_profit' => $totalProfit,
            'rows' => $rows,
        ];
    }

    public function createDailyIncomes(array $rows, int $totalId,$model): void
    {
        foreach ($rows as &$row) {
            $row['daily_income_total_id'] = $totalId;
        }

        $model->insert($rows);
    }


    public function createTotal(array $request, array $totals,$model)
    {
        return $model->create([
            'voucher_no' => $this->generateVoucherNo(),
            'total_price' => $totals['total_price'],
            'total_investment' => $totals['total_investment'],
            'total_profit' => $totals['total_profit'],
            'note' => $request['note'] ?? null,
            'is_instant' => !empty($request['is_instant']),
            'created_by' => Auth::id(),
        ]);
    }


    //Update Section
    public function getTotalIdFromIncome(string $id,$model): int
    {
        return $model
            ->findOrFail($id)
            ->daily_income_total_id;
    }

    public function updateTotal(int $totalId, array $request, array $totals,$model): void
    {
        $model->where('id', $totalId)->update([
            'total_price' => $totals['total_price'],
            'total_investment' => $totals['total_investment'],
            'total_profit' => $totals['total_profit'],
            'note' => $request['note'] ?? null,
            'is_instant' => !empty($request['is_instant']),
            'updated_by' => Auth::id(),
        ]);
    }

    public function replaceDailyIncomes(int $totalId, array $rows,$model): void
    {
        // delete old children
        $model
            ->where('daily_income_total_id', $totalId)
            ->delete();

        // attach total id to new rows
        foreach ($rows as &$row) {
            $row['daily_income_total_id'] = $totalId;
        }

        // insert new rows
        $model->insert($rows);
    }

    //Private Section

    private function toFloat($value): float
    {
        return (float) str_replace(',', '', $value);
    }


   private function generateVoucherNo(): string
    {
        return 'VOU-' . date('Ymd') . '-' . strtoupper(uniqid());
    }
    
}
