<?php

namespace BasicDashboard\Web\Products\Services;

use BasicDashboard\Foundations\Domain\Products\Product;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Products\Resources\ProductResource;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\ResponseFactory;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;
use Exception;

/**
 *
 * A ProductService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ProductService extends BaseController
{
    const VIEW = 'admin.product';
    const ROUTE = 'products';
    const LANG_PATH = "product.product";

    public function __construct(
        private Product $product,
        private ResponseFactory $responseFactory
    )
    {
    }

    public function index(array $request): View
    {
        $productList = $this->product
            ->filterByKeyword($request['keyword'] ?? null)
            ->orderByLatest()
            ->paginate($request['paginate'] ?? config('numbers.paginate'));

        $productList = ProductResource::collection($productList)->response()->getData(true);
        return $this->responseFactory->successView(self::VIEW.".index", $productList);
    }

    public function create(): View
    {
        return view(self::VIEW.'.create');
    }

    public function store($request): RedirectResponse
    {
        try {
            \DB::beginTransaction();
            $request['created_by'] = Auth::id();
            
            if (isset($request['photos']) && is_array($request['photos'])) {
                $request['photos'] = $this->uploadPhotos($request['photos']);
            }

            $this->product->create($request);
            \DB::commit();
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_created'));
        } catch (Exception $e) {
            \DB::rollBack();
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

    private function uploadPhotos(array $photos): array
    {
        $paths = [];
        foreach ($photos as $photo) {
            $path = $photo->store('products', 'public');
            $paths[] = $path;
        }
        return $paths;
    }

    public function edit(string $id): View | RedirectResponse
    {
        $id = customDecoder($id);
        $product = $this->product->findOrFail($id);
        $product = new ProductResource($product);
        $product = $product->response()->getData(true)['data'];
        return $this->responseFactory->successView(self::VIEW . ".edit", $product);
    }

    public function show(string $id): View | RedirectResponse
    {
        $id = customDecoder($id);
        $product = $this->product->findOrFail($id);
        $product = new ProductResource($product);
        $product = $product->response()->getData(true)['data'];
        return $this->responseFactory->successView(self::VIEW . '.show', $product);
    }

    public function update($request, string $id): RedirectResponse
    {
         try {
            \DB::beginTransaction();
            $decodedId = customDecoder($id);
            $product = $this->product->findOrFail($decodedId);

            $existingPhotos = $request['existing_photos'] ?? [];
            $newPhotos = [];

            if (isset($request['photos']) && is_array($request['photos'])) {
                $newPhotos = $this->uploadPhotos($request['photos']);
            }

            // Identify and delete removed photos from storage
            $oldPhotosInDb = $product->photos ?? [];
            foreach ($oldPhotosInDb as $photo) {
                if (!in_array($photo, $existingPhotos)) {
                    \Storage::disk('public')->delete($photo);
                }
            }

            // Final list of photos: kept existing + new uploads
            $request['photos'] = array_merge($existingPhotos, $newPhotos);
            unset($request['existing_photos']);

            $product->update($request);
            \DB::commit();
            return $this->responseFactory->successShowRedirect(self::ROUTE, $id, __(self::LANG_PATH . '_updated'));
        } catch (Exception $e) {
            \DB::rollBack();
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

    public function destroy($request): RedirectResponse
    {
         try {
            \DB::beginTransaction();
            $id = customDecoder($request['id']);
            $product = $this->product->findOrFail($id);
            
            // Delete local images
            if ($product->photos) {
                foreach ($product->photos as $photo) {
                    \Storage::disk('public')->delete($photo);
                }
            }

            $product->delete();
            \DB::commit();
            return $this->responseFactory->successIndexRedirect(self::ROUTE, __(self::LANG_PATH . '_deleted'));
        } catch (Exception $e) {
            \DB::rollBack();
            return $this->responseFactory->redirectBackWithError($e->getMessage());
        }
    }

}
