<?php

namespace BasicDashboard\Web\Products\Services;

use BasicDashboard\Foundations\Domain\Products\Product;
use BasicDashboard\Foundations\Shared\BaseCrudService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Filesystem\FilesystemManager;
use Illuminate\Support\Facades\DB;

/**
 *
 * A ProductService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ProductService extends BaseCrudService
{
    protected bool $useDecoder = false;

    public function __construct(
        Product $product,
        private FilesystemManager $filesystemManager
    ) {
        parent::__construct($product);
    }

    public function store(array $request): Model
    {
        return DB::transaction(function () use ($request) {
            if (isset($request['photos']) && is_array($request['photos'])) {
                $request['photos'] = $this->filesystemManager->uploadFilesToLocal($request['photos'], 'products', 'photos');
            }

            $categories = $request['categories'] ?? [];
            unset($request['categories']);

            $product = parent::store($request);
            
            if (!empty($categories)) {
                $product->categories()->sync($categories);
            }

            return $product;
        });
    }

    public function update(array $request, string $id): Model
    {
        return DB::transaction(function () use ($request, $id) {
            $product = $this->findOrFail($id);

            $existingPhotos = $request['existing_photos'] ?? [];
            $newPhotos = [];

            if (isset($request['photos']) && is_array($request['photos'])) {
                $newPhotos = $this->filesystemManager->uploadFilesToLocal($request['photos'], 'products', 'photos');
            }
            
            $oldPhotosInDb = $product->photos ?? [];
            $this->filesystemManager->deleteFilesFromLocal($oldPhotosInDb, $existingPhotos);
            
            $request['photos'] = array_merge($existingPhotos, $newPhotos);
            unset($request['existing_photos']);

            $categories = $request['categories'] ?? [];
            unset($request['categories']);

            $product = parent::update($request, $id);

            if (!empty($categories)) {
                $product->categories()->sync($categories);
            }

            return $product;
        });
    }

    public function delete(string $id): void
    {
        DB::transaction(function () use ($id) {
            $product = $this->findOrFail($id);
            if ($product->photos) {
                $this->filesystemManager->forceDeleteFilesFromLocal($product->photos);
            }
            parent::delete($id);
        });
    }
}
