<?php

namespace BasicDashboard\Spa\Products\Services;

use BasicDashboard\Foundations\Domain\Products\Product;


/**
 *
 * A ProductService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ProductService
{
    public function __construct(
        private Product $product,
    )
    {
    }

    public function fetchHomeData(array $request)
    {
        $bannerData = $this->product->getBannerData(4);
        $miniBannerData = $this->product->getMiniBannerData(4);
        $NormalData = $this->product->limit(10)->get();
        $NormalDataTwo = $this->product->limit(10)->get();
        return [
            'bannerData' => $bannerData,
            'miniBannerData' => $miniBannerData,
            'normalData' => $NormalData,
            'normalDataTwo' => $NormalDataTwo,
        ];
    }

    public function paginate(array $request)
    {
        $keyword = $request['search'] ?? ($request['keyword'] ?? null);

        return $this->product
            ->filterByCategory($request['category_id'] ?? null)
            ->filterByKeyword($keyword)
            ->orderByLatest()
            ->paginate($request['per_page'] ?? config('numbers.paginate'));
    }

    public function findOrFail(string $id): Product
    {
        return $this->product->findOrFail($id);
    }
}
