<?php

namespace BasicDashboard\Spa\Products\Services;

use BasicDashboard\Foundations\Domain\Products\Product;


/**
 *
 * A ProductService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ProductService
{
    public function __construct(
        private Product $product,
    )
    {
    }

    public function paginate(array $request)
    {
        return $this->product
            ->filterByKeyword($request['keyword'] ?? null)
            ->orderByLatest()
            ->paginate($request['paginate'] ?? config('numbers.paginate'));
    }

    public function findOrFail(string $id): Product
    {
        return $this->product->findOrFail($id);
    }
}
